"use client"

import { useState, useRef, useEffect } from "react"
import { Plus, Trash2, Download, Eye, Edit2, X, Check } from "lucide-react"

// ─── SGH Logo Base64 ──────────────────────────────────────────────────────────
const SGH_LOGO_B64 = "/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAACWKADAAQAAAABAAABaAAAAAD/wAARCAFoAlgDAREAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9sAQwACAgICAgIDAgIDBQMDAwUGBQUFBQYIBgYGBgYICggICAgICAoKCgoKCgoKDAwMDAwMDg4ODg4PDw8PDw8PDw8P/9sAQwECAwMEBAQHBAQHEAsJCxAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ/90ABABL/9oADAMBAAIRAxEAPwD9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/9D9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/9H9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/9L9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/9P9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAE3L60AGRQBzOoeNPCGkbv7W1uxsdnX7RcxRY/77YUAcxL8a/g5Ads/jvQYz6NqloP5yUAT23xf+E96/l2fjPRbhvSPUrZv5SUAdlp+taRqy7tLvYbtfWGRZB+ak0AamRQAtABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH//1P38oAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAz9T1PTtHsptS1a6isrS3XfJNPIscaKO7MxAA+poA+B/i1/wAFOf2SvhWZrSHxM3jDUYtw+zaDGLwEqccXDNHbHn0lJ9utAH5u/Ej/AILY+N74yWvwm8AWOlJjatzq88l45Jxz5MPkhCP+ujj69aAPiHxr/wAFKf2x/G8jrN8QJtGtz92LSoIbIA4xkSogm/8AIh/GgD5e8R/Gj4ueMnkbxf401rWvN+8LzUbi4X/vl3IoA85lnkmfzJXLn1f5moAjx7D8qADHsPyoAu2Oqalpsom066ltXXkNE7I35qRQB7b4S/am/aN8DyB/C/xK8QWKDpENSuGg/wC/TuU/JaAPrXwD/wAFZv2u/BzQxa1q+neLraI42anYxoxT0D2n2ck+7FqAPvb4Yf8ABa7wTqDxWXxe8BXmkE/K13pE6XkZz/EYZvJdAPaRz9etAH6Y/B/9sX9nD45CGH4eeOLC7v5wMWFw5s73JOMC3nCO+PVQR79aAPpwHNAC0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB//9X9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgDz74jfFP4efCTw5L4t+Jev2nh3SYsAzXcgQOx6LGv3pHPZEBY9gaAPxS/aF/4LNWFsbrw/wDs4+HvtbYZBrOsKyR9B80FojByOcq0rqQRgxUAfjN8Xf2j/jX8ddQa/wDip4vvtdUsXW2eXy7OMk5JjtY9kMZ/3EFAHiVABQAUAFABQAUAFADgrN92gBD8v3qAEwPUfnQAg+b7tAEqtJGQy5Vl6H0oA+4vgV/wUS/ae+BUlvZad4mfxNoURCnTdbJvIggOdschImiAycBJAo/u+oB+4H7On/BV34BfF57XQPiIT8OfEU2xAL+VX06VzgfJeYRUGSSfOWIDoCxoA/UW1u7a9t47qzlWeGVQ6OhDKytyCCOCCOlAFmgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD/9b9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAguLiC0gkubqRYoolLO7HaqqvJJJ4AAoA/Gv8Aaz/4K1eB/hy174I/Z7ig8YeIEzHJq0jMdKtiR1i2YN0R6o6xjIId+VoA/nz+Knxl+J3xs8TS+L/ij4huvEGpyH5WuH/dxD+5DEuI4k77I1VQc4AzQB5lQAUAFABQAUAFAHaeBvhx49+JOrLoXgDw/f8AiLUGYDybC2kuXGe7CNWIHqTxQB+iXww/4JHftU+OI4r3xXDp3gi0lyxGo3ImuCvbEVt5oyfR2T60AfevgP8A4In/AAu05YZfiL4/1XWZBy6adBDp6H0BMv2oke420AfUmgf8Ex/2I/BkK3Op+ETqjrnM2qaldNn/AIAsscf5IKmTjH4jWEKk5ctOPMddb/AX/gnx4RG2bwv4Bt2j/wCfoWUrf+R2dq55YqgviqR/8CPZpZHmdT+Hhakv+3Zf/IlwWP8AwT4tV+zrpPw6Uf3RZaZ/8brL67hl/wAvInox4Uzx/wDMHU/8BkUpvhn/AME7vEwKtoHw7laT+5Dp0Lf+O7GojjMNL4akf/AjCpw5nEPiwdT/AMFyOdv/ANgL9grx9EwsPBumCV8Yk0rUbiFhj0EM4QfTbXVGcH8MjxquCxNH+NTlH/FE8C8a/wDBGT9nnXA8vgzxJr3hqduNrvDe2w46hHjSU/jN+danAfDnxJ/4Ix/Hjw4klz8NvEmk+MYFJ2xSl9OunGMjCSGSHr3My/T1APL/AIcfGT9uf/gnzqMel+LNA1SPwiHKyaXq8bz6Ux3AN9lu4/MSJ+Cf3LkEnLq+MUAfvP8Assftz/Bf9qewjs/DV4dF8WLGZLjQ711W4AQ4ZoG6TpjnKfMBguiZGQD7ToAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD//X/fygAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA8s+L3xk+HfwM8FX3j74l6vFpGk2anBbLSzyAEiKGNQWeRsHCqDxknABIAP5eP2yf8Agon8Tf2mby58K+Gmm8JfDwNtXTonxPegEkSX0inBJ6iJTsU4yXZQ9AH5y0AFABQAUAFABQB9N/s//sgfHf8AaUvlT4Z+HZJNLV9k2q3ZNvp0PXO6Zh85HdIw745CkUAfuf8AAL/gj58GfAq2+sfGrUZvHmrIRIbWMtZ6YjAnAwhE0uOOWdVPdBQB9o6z8cf2YP2btJPhLQpNP04WmANJ0K2QuG6EFIQsaNxn94yZ65rya+Y4aj8UvePv8o4LzrMveo0eWn/NL3Y//bf9unyL45/4KQ+Irpntvhx4VhsY8bRcanI0zknv5MWwKR/10YV89VzyUv4MT9oy3wnoL3swxEpf3Y+7/wCTS/8AkT5Q8WftWftAeL2kGo+M7uzjYYEVjts0A+sCo/5tXjTzHFT+KofqGC4KyHCfw8LGX+L3v/SjwrUdY1fWZjcazfXGoynkvczPM5/GRmNebJyl8R9rQoUqMeWjGMf8MeX/ANJMtY41+6ij6CpOvmkPoIDav8QDfhQAkZNu3mQny3HdTg/mKAlr7sj07w18Z/i34QIHhrxjqtjGMARC7d4RjGMRSFk/8drqhiq9P4akj5zGcP5Vi/8AeMLTl/27H/0qJ9N+Df8AgoF8bNAKReJYrDxPAoUHzovss5APOHhGwcesRPv6ezSznEw+L3j84x/hfk1f3sPKVKX/AIFH/wAm/wDkj7E8Fft6fBDx1bnRfH9jP4aa6AjkjvIhd2MgccqXjDEjsd8SiveoZzQn7tT3T8hzTwxzfDc0sHKNWP8Ad92X/gMv/bZHKfEX/gnt+yz8bRB8Q/hJOPA3iBJDPaa34TuAkKzqQ6uIYm8kFW5/deW+f4wa96E4zjzRkfj+IwtfDTlRxFOUZfyy909C+HPjj9oH4HrF4P8A2mIo/Fvh2ArFaeOdJibaF/h/tmz/ANZbn/p6j3Qf89WX7zanGfbttc295bx3VrIs0Mqh0dDlWVhkEEcEEUAWKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAP/9D9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAPnD9pf9pv4c/svfD+fxt48ug88uY9O06Jh9qv58fcQc7UXIMkhGFHqxVWAP5I/2kv2nPid+0947m8Y/EO+xbxM66fp0JK2enwMchIlJOWPG92JZiBzgKAAfO1ABQAUAFABQB1vgjwJ4v8AiP4msvB3gTSbnW9a1FtkNraxl5GPcnsqqOWYkKoBJIAJoA/oJ/ZO/wCCRfhXwpHaeNf2l5E8QavxJHoNu4OnwHggXEgJNww7qpWMcg+aDmgD70+K37Vnwa+AVgvgzw1bxarqenL5MWk6WEigtQgGEkdR5cKgHG1QzD+5ivExWaUMP7vxSP1Ph7gPM825a0v3VH+aX2v8Mftf+k/3j8u/if8AtTfGv4z3EmlS6lJpunSnA0vSA8SFeMiVxiaUHHIJCH+4K+NxGY18R7vN7v8ALE/prJuC8myePtvZ80v+flT+uWP9e8cXoH7Onxz8RojaN4F1V4pThWlgNqh/4FP5Y/WueGCxM/hpyPXxHFWS4f8AjYyn/wCBc3/pPMepWP7DX7SF4gaXw9b2anr51/b/AMkdq7Y5Ri39k+cn4jcPQ+GtKX+GMjcX9gL9oULu+y6Xn0/tA/8Axqq/sbF/3Ti/4iZkP81T/wAB/wDtjIu/2Fv2kbZTJFoNpdkdodQgH/o0xn9BUyyfF/ynVDxI4en8VaUf+3ZHmWufs1/Hrw8skmp+BdUKRHBa3i+1D87cyCuKeAxMPipyPpMPxbkdf+HjKf8A29Ll/wDSuU8Zv7C90uc2mqW0tlOOsc8bROPqrAEflXHKMl7sj62lVp1I81OXNH+6Vag1CgAoAKACgDsfBPxC8bfDrVBq/gbWrrRbkEhjbuRHJ7SRHMcgHo6ke1b0q9SnLmpy5TyMxyvB5hS9jjqMakf73/yXxRP0p+DX/BQ2GdoNE+NWni3LYT+1bFC0eSes0Ayy8dTGGBP8CgZP1eFzv7OIj/28fzxn3hbJc1bJ6nN/07l/7bL/AOS/8CP0l8Iax4W13QLTVfBt3a3ukXK74ZbN1eFgfQrkD6V9bCcZx5qcj+dsVha+Gqyo4inKMo/ZkdTWpxBQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH/9H9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoA+e/2kv2jfh9+zJ8Nbz4h+PJ9xXENjZIwFxfXbA7II+D7szYIVQzYOMEA/kB/aF/aD+If7SPxGvviL8Q7wyTyny7W1Qn7PZWwJKwQKSdqrn6kksxLEkgHhtABQAUAFABQB9Nfsxfsp/FL9qbxoPDPgO0MOn2pB1LVZ1P2WxiPdzxvkbBCRqcse6qHdQD+oz4Ifs9fs/8A7Dnw5nvLAxWk7xqup65eqpvb5xyEUgFghb/VwJnnH33JZsqtWFOPNUPRwGAxONrxw+FjzSl/X/gJyPi6b9pj9o1n0nwTbSfC7wLN8pvtR3Ratfx/3vJi/eQxuv8ADujb+838NfPVfrmL92n+7p/+TH7BgI8OcPfvMZL63iY/Zj/Dj/298Mv/ACb/AAmp8Pv2Afgv4UWO58Um68W3iEn/AEqQw24J6FIoNh49Hd6uhk1CH8T3jlzTxMznE+7heWlH+770v/Apf/an194a8D+D/Btstn4T0Wz0eBQBstIEhBx6hAM17lOlTp/w48p+VYzMMZjJc2KrSqS/vS5jqdq+lbnmhtFAC0AJgUAG1fSgDnvEHhPwx4qtTZeJtJtNWt2GPLu4EnXn2cEVlOlTn7so8x34XG4nDS9ph6kqcv7suU+SPHv7BvwO8WrJPoFrP4TvCBh9PfMBI/vQSblAx2TZ9a8OrlGGn8Pun6hlfiTnWE92tKNWP974v/AonwN8UP2E/jH4EWXUfDSR+MdOQ5Bsh5d0ATj5rdjk9uI2c/TpXzuIyivT96PvRP3PJvEjKMb+7xH7qp/e+H/wL/5LlPjC6trmyuJLO9heCeA7ZI5FKOp9GVhkH2NfPH6/GpGceaPwkFBYUAFABQB6v8KPjb8Qvg1rI1XwRqTQwuwa4s5R5lrcZGMOh7+jKQw7MMnPbh8VVoS5qcj5bO+Hsvzil7HGU/8ADL7Uf8Mv6iftX+z9+1R4H+OdrHpkbDR/FMce6bTZnBLbQN7wPx5qeuAGXuAME/fYLMYYn3fhkfx7xRwXjskl7T+JR/m/+S/lPqUHNeyfmwtABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB//S/fygAoAKACgAoAKACgAoAKACgAoAKACgAoA4j4i/EHwr8K/BOsfEHxtfLp2iaJbtcXMzdlHAVR1ZmYhVUZLMQoBJAoA/jr/a7/am8WftVfFW58a60JLHRbQvBo+mM+5LK0LdTjgyyAK0rDqQADsVAAD5WoAKACgAoAKAPsj9jn9jrx3+1j47Gl6Ur6Z4V0p0Or6sUzHCjZPlRFgVeeQA7RyFHzEEYBAP63PhH8I/AXwS8D2Hw9+G+mJpekWCjhcGSaTADSzPgF5WwMk+wACgAAHUTeENBu9di8R39sLq/tgVtpJv3gt8/eMKtkRs2MMygEjgkjisvZR5uY7442vChLD05csZfF/e/wAX83/pJ04GK1OAWgAoAKACgAoAKACgAoAKAExxigDwv4t/s6/C34zWrDxbpax6kEKxajbBYryPIx/rMHeBjhXDKDzjPNebiMFQr/xIn2WR8VZnk8v9lqe7/LL3o/8AgP8A8ifj18ev2RPiH8Fjca1bKfEXhWIlhqFuhEluhJAFzFyUwP4wWTuSpIFfDYzLKtD3viif1jwzxzl+cctGX7ut/LL7X+GX2v8AD8R8o14x+ohQAUAFAFzT9Rv9KvoNT0q5ks7u2YSRTQsUeN15BVlwQR2Iqoykpc0TKrShUhKnUjzRkfsT+yh+2TB4/e2+HXxSuI7bxKSI7O+OEi1AYACMMAJPngAfK5+7tJCH7jLs09p+5rfEfyVxpwDLAc2YZXHmo/aj9qP/AMlH/wBJP0SHSvqj8FFoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA//9P9/KACgAoAKACgAoAKACgAoAKACgAoAKAE7UAfy/8A/BUz9saX4v8Aj2T4H+A70/8ACG+DrhlvJYXzHqOpxFkc/LwYoMlF7Ft7cjYQAfkZQAUAFABQAUAfRn7L37NvjT9qH4q2Pw68JRmG1H7/AFPUGQtFY2SkCSVvVjkLGmRuYgEgZYAH9ifwc+D3gj4FfD7S/hr8PbEWOk6ZGAT1lnlIG+eZhjfLIRljgADCgBQqgA9VoAKACgAoAKACgAoAKACgAoAKACgAoAKAIZoY54zDKodGGCpGQRQXGUl70T8xv2mP2GbTU0vPHXwVt1tLwAyXOjLxDLgZLWo/gfj/AFY+Vh90Bhh/kMflF/3mH/8AAT+i+EPEaVPlwOcS5o/Zqfy/4v5o/wB74v8AEfk1cW1zaXEtpdxPBPC7I8cilXRlOGVlbBBB6g18Uf1HGUZx5okdBYUAFADgzKdykqy/MCO1AH7EfsbftZnxrHbfCr4l3mfEMC7NPvZWx9uRFz5UjH/luoBIYn5wOfnGX+6yvMvafua3xH8lcfcEfU5SzTLY/uftR/l/vR/u/wDpP+E/R0HNfVH4ALQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH/9T9/KACgAoAKACgAoAKACgAoAKACgAoAKAPzi/4KUftUn9nT4JS6J4YvPI8a+NhLY6cUI8y1gC/6TdYJyDGrKqEch3U8hSKAP5KmbcWZqAG0AFABQAUAbvhXwtr/jXxHpvhHwvZSalq+r3Edpa28S7nlllYIiqPUsQKAP7Gf2MP2VvDn7KnwhtPCVqsdz4k1ILda3fAAme7I4jVsA+VADsjHA6vgM7ZAPr6gAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgBNooA+Cf2tf2SbL4n2Vz8QPh/brbeL7ZN00CgLHqca/wt0CzgfcfofuNxtZPmsyy2NaPtKfxf+lH7dwRxvUy2ccDjpc2Hl8P/Tv/AO1/mj/29E/FO4trm0uJbW6jeGeB2SSN1KujKdrKynkEHgg9K+AP7DhKM480fhIqCwoAKAJ7W5uLK4hvbKV4Z7d1kikjba6OhDKykcggjIIojoROEZxlGUfdkfu9+yL+0ZF8bPCDaNr7qni/Qo1W8AOPtUQO1LpBgD5uBIB91+wVkz+kZbjfbw5ZfFE/iPjnhSWTYr22H/3ep8P93+7/API/3T7Dr3D8qCgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA//V/fygAoAKACgAoAKACgAoAKACgAoAKAKt5d21jazXt5KsMFujSSOxwqqoyST2AHJoA/jK/bX/AGiL39pT4/6/46jmkfQrJzYaLGxICWFuzBG2EnaZWLSkdQXx0AoA+SqACgAoAKACgD+gH/gj/wDsnxx29x+1F42s8ySebZeHI5UIKqCY7q8UnruwYYz6ebkYKmgD98gMUALQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAJtFAHwp+0J+xPofxh8WR+NfDGqxeGdTuV26hm2E0d0VGFl2q8eHwAGPOQBwDkn5zG5THET9pTlyn7Twr4g18pwn1PEU/axj8PvcvL/AHf8P/pJ4B/w7R13H/I+23/guf8A+SK87+wZf8/P/JT7z/iLlD/oDl/4M/8AtQ/4do67j/kfbb/wXP8A/JFH9gy/5+f+Sh/xFyh/0By/8Gf/AGof8O0ddx/yPtt/4Ln/APkij+wZf8/P/JQ/4i5Q/wCgOX/gz/7UP+HaOu4/5H22/wDBc/8A8kUf2DL/AJ+f+Sh/xFyh/wBAcv8AwZ/9qdz8NP2FvHXws8baZ448O/EG2F3p0gJjbT32TxMQJInxcdGGR7HDDkCt8PlFWjUjUjU/8lPDzfxIwOaYOpgcRg5csv8Ap58Mvsy+H7J+mI6V9afzsLQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAf/W/fygAoAKACgAoAKACgAoAKACgAoAKAPzL/4KpfHx/g/+zZd+E9GuTDr3xCkbSYShKutkV3Xjggjgx4hPp5oPXFAH8n9ABQAUAFABQB7X+zr8F9b+P3xl8MfCnRAytrdyq3MygsLe0T555jgH7kSswBxkgDOSKAP7YvBnhHQfAfhXSfBfhe1Wy0nRLaK0tYVHEcUKhEX8AAKAOnoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA//1/38oAKACgAoAKACgAoAKACgAoAKAE7UAfydf8FWPjO3xQ/al1HwxYzebpPw/hXSIguMfaQd943BJ3CQ+UfXygelAH5o0AFABQAUAFAH9Dn/AARh+Aq6f4a8TftDa1bg3GrOdG0pmAyLaAq9zIvGcPKFTrwYmHc0AfuxQAUAFACZFAHmfjf4yfC/4cADxr4nsdJk/wCeMsoM54zlYVzIR7hTXLVxVCj/ABJcp9Dl2Q5nmH+54eVT/t33f/AvhPnLV/2/P2fdOleKzu9R1MJj5raxdQf/AAIMNeRLOcIj9AoeGWfVI80oxj/il/8AI8xzLf8ABRr4KhsLo+uEev2e3/8AkisP7cofyyPSj4VZz/z8p/8AgUv/AJEb/wAPGvgvn/kDa5/4D2//AMkUf25Q/lkX/wAQpzn/AJ/U/wDwKX/yIf8ADxr4L5/5A2uf+A9v/wDJFH9uUP5ZB/xCnOf+f1P/AMCl/wDIh/w8a+C+f+QNrn/gPb//ACRR/blD+WQf8Qpzn/n9T/8AApf/ACIf8PGvgvn/AJA2uf8AgPb/APyRR/blD+WQf8Qpzn/n9T/8Cl/8iH/Dxr4L5/5A2uf+A9v/APJFH9uUP5ZB/wAQpzn/AJ/U/wDwKX/yIf8ADxr4L5/5A2uf+A9v/wDJFH9uUP5ZB/xCnOf+f1P/AMCl/wDIh/w8a+C+f+QNrn/gPb//ACRR/blD+WQf8Qpzn/n9T/8AApf/ACI5f+Ci/wAGXICaLrpJOABb25JPp/x8Uf25Q/lkR/xCnN/+f1P/AMCl/wDIn3Zot/Nqmk2mo3FnLp8l1EkjW9wFEsRcZ2OEZlDDOCAxwe9fTQlePMfidalGlVlTjLm5ftR+GRqVRgFABQAUAeafEL4xfCz4UWRv/iR4s0zw1Dt3KL+7igd/ZEdgzH2ANAHxT4s/4Ks/sb+GJZLez8S3niGSL7w07T52B+j3AhQ/g1AHkt1/wWf/AGY4nK23h7xRMPX7JZj/ANvKAK//AA+j/Zq/6FjxR/4DWf8A8lUAH/D6P9mr/oWPFH/gNZ//ACVQAf8AD6P9mr/oWPFH/gNZ/wDyVQAf8Po/2av+hY8Uf+A1n/8AJVAB/wAPo/2av+hY8Uf+A1n/APJVAB/w+j/Zq/6FjxR/4DWf/wAlUAaWi/8ABYn4A+I9Xs/D+g+DfFl/qeoypBa28VrZtLNNKdscar9q5ZmIUD19aAP1lspp7mzt7i4ga2llRWeJiGaNmGSpK5BweMjg9qAPy6+Iv/BWv9n/AOGnj7xF8PNd8PeIptQ8NX9xp88lvb2rQvJbSNE5Qvco2Ny/xKD7UAcb/wAPo/2av+hY8Uf+A1n/APJVAB/w+j/Zq/6FjxR/4DWf/wAlUAfR/wCzB/wUG+En7Vnj2++H3gLR9Y0+/sNPk1F5NQit44mijljiYKY55GLbpV42jjPPFAH3pQAUAFABQAUAFAH51ftDf8FKfgx+zd8UL74U+NNC1y91Owht52msobd4CtwgkABkuI2yFIz8vWgDxH/h9H+zV/0LHij/AMBrP/5KoAP+H0f7NX/QseKP/Aaz/wDkqgD1/wCA3/BTr4JftCfFXRfhH4O0LXrTVtb8/wAqW8gtktx9nged8slxI/3I2x8tAH6RjpQAtABQAUAFABQAUAFABQAUAFAH/9D9/KACgAoAKACgAoAKACgAoAKACgDhPib44sPhp8O/EvxB1Tb9k8OaddahIGO3cttE0pXPqduB7mgD+GHxHr2o+KPEGp+JtZl87UNWupru4f8AvzXDmSRvxZiaAMSgAoAKACgC9pdheavqNrpWnRNPd3sscEMaD5nkkbaqj3LEAUAf3C/AH4W2PwW+DPg/4WWIXHh3TobeVl6SXBG+eTAAx5krO+O27FAHsNABQBR1HULPSrG41PUZktrS0jaWWV22oiINzMxPAAAyTUylFR5pGtKlOpONOnHmlI/G39oj9uTxR4vvbnwt8Irt9D8PxFkbUE+S8uyCMNG55gTI4KgSHg7lyUHwWNzepP3aPuxP624V8OcNhaccVm0faVv5fsx/+Sl/5Kfn5PPPcTvdXMrTTSnLSOxZ2PqzNya+aP3aMYqPLH4SKgsKACgAoAKACgAoAKACgD9Bf2EfgGPG/io/FbxLbiTRPDkuLFGyBcX65G8Y6rBjI/6aFcH5GFfS5Rg/aT9tL4Yn4P4k8T/U8J/ZeHl+8qfF/dj/APbf+k/4j9oh0r78/kMWgAoA8Z+Nvx8+Fn7PXg+Xxv8AFPWo9KsQSkEf37i6l7RQRDl3P4BRlmKqCQAfztftJf8ABWr41fE+5udC+Dgb4e+G2yiyoVk1WdOPmaf7sBOMgQ/OhziVhQB+Vmta7rPiPUZtY8Q39xql/cndLcXUrTzSN6tJISzH3JoAyaACgAoAKACgAoAKACgD99f+CRv7HhLD9qT4g2WAPMg8NW0ydfvRT33P4xR8f32x9xqAP3+HSgD+JX9rnP8Aw1H8V8/9DRq3/pVJQB87UAFAH69f8EXP+TnvE/8A2Kl3/wCltlQB/T1QAUAFABQAUAFAH8mP/BWPP/DZ/iT0/s/SP/SRKAPzZoAKAPvv/gl9/wAnw/Dr6ap/6bbqgD+vgdKAFoAKACgAoAKACgAoAKACgAoA/9H9/KACgAoAKACgAoAKACgAoAKACgD81P8AgrB8Q28Dfsga1pNvKIbnxff2WkIf4tpc3UuPrHbsp+tAH8m1ABQAUAFABQB9x/8ABOT4ZL8T/wBr3wLYXcYksdDnfWrncMgDT1MsRIz0M4iU/wC9QB/YgOlAC0AFAH5lf8FDvi9d6Noel/CDRp2hk1tftmosjEMbZG2xRcHpJIpJ9AmOjV8hneIkoxw8ftH9FeFmRxrVambVo/w/dj/i+1L/ALdj/wClH5GV8Uf1UFABQAUAFABQAUAFABQAUAei/Cf4aa78W/HumeBNAGya/kBmlYErb26EebK2Oyg8DjLEKDkiurD0JVqsacT57O83oZVgamOxH2f/ACaX2Yn9GvgXwboXw+8J6Z4N8NQ+Rp2lQrDEucscfeZj3Z2yzHuxJ71+pUqUadONOmfwBmOPr4/F1MZiJc0qkjrq6DywoA+dv2mf2j/A/wCzD8Lr/wCIvjOUSyr+50+wVws19dsCUiTOcDALO2DtUEgE4UgH8gXx9/aD+JP7Rvj678f/ABJ1E3Ny5ZLW2UkW9lBklYIEydqL9SScsxLEkgHiNABQAUAFABQAUAFABQAUAfYv7Ef7LGq/tUfGWz8LSK8PhbSCl5rt0uV8u0BOIkYA/vZmGxPT5nwQhFAH9i+gaFpXhjRbHw7oNrHY6bpkEdtbQRDCRQxKERFHYKoAA7CgDYoA/iU/a5z/AMNR/FfP/Q0at/6VSUAfO1ABQB+vX/BFz/k57xP/ANipd/8ApbZUAf09UAFABQAUAFABQB/Jj/wVjz/w2f4k9P7P0j/0kSgD82aACgD77/4Jff8AJ8Pw6+mqf+m26oA/r4HSgBaACgAoAKACgAoAKACgAoAKAP/S/fygAoAKACgAoAKACgAoAKACgAoA/Aj/AILdeMj5Xww8AQN8rtqOpTgk9VEcER9P4pf19KAPwCoAKACgAoAKAP3O/wCCI/gYXXjT4k/EaWIf8S2wstLic9c3krzSAfQW6fnQB/RNQAUAJ2oA/n6/bO199f8A2j/FmTmPTjbWMYx0WOBC3/j7sfxr80zSd8XUP7p4AwsaHD2H/vc0v/ApHy7XjH6WFAHsPww+AnxX+L6zT+AtCa8tIGKSXckkcNuHGMgPIRuPI4XJ9R0rvw+Dr1/4cT5LOOJssynljjq3LL+X4pf+AxPav+GCP2is/wDIO07/AMD4/wDCvQ/sfF/ynyH/ABEvh/8A5+S/8BD/AIYI/aKz/wAg/Tsf9f8AH/8AE0f2Pi/5Q/4iXw//AM/Jf+Ah/wAMEftFZ/5B+nY/6/4//iaP7Hxf8of8RL4f/wCfkv8AwEP+GCP2is/8g/Tsf9f8f/xNH9j4v+UP+Il8P/8APyX/AICH/DBH7RWf+Qfp2P8Ar/j/APiaP7Hxf8of8RL4f/5+S/8AAQ/4YI/aKz/yD9Ox/wBf8f8A8TR/Y+L/AJQ/4iXw/wD8/Jf+Agv7BH7RWf8AkH6d/wCB8f8AhR/Y+L/lD/iJfD//AD8l/wCAn6Mfsifs3zfA3wtdal4nSJ/FmtHFy0TB44IFI2QxvgEjI3seMkgEfKDX0+W4D6tDmqfFI/n/AI44rjnWJjTwv+70/h/vS+1L/wBtifYte8fk4UAQySJGjSSEKqjJJPAoA/j2/wCCgH7UV7+0t8ddQvdOumk8HeGHl0/RIsgIYlf95c8fxTsA2eDsCKeUyQD4aoAKACgD3D4T/s1/HP43Mx+FngrUdfgQgNdRReXaKx/ha5l2Qq3sXBoA+w9P/wCCSP7Yt7brLc6RpVjIeTHNqkTMPxhEiH/vqgC//wAOhP2v+v2TQ/8AwZj/AONUAH/DoT9r/r9k0P8A8GY/+NUAH/DoT9r/AK/ZND/8GY/+NUAH/DoT9r/r9k0P/wAGY/8AjVAB/wAOhP2vuv2TQ/8AwZj/AONUAfv/APsa/sw6H+yx8GdP8D22y51+9Au9avVwTcXrjlVbAPlQg7IxgZALkBnagD6zoAKAP4lP2uc/8NR/FfP/AENGrf8ApVJQB87UAFAH69f8EXP+TnvE/wD2Kl3/AOltlQB/T1QAUAFABQAUAFAH8mP/AAVjz/w2f4k9P7P0j/0kSgD82aACgD77/wCCX3/J8Pw6+mqf+m26oA/r4HSgBaACgAoAKACgAoAKACgAoAKAP//T/fygAoAKACgAoAKACgAoAKACgAoA/l3/AOCyviKTVP2otI0QN+50bw3aJj0ee4uJW/QigD8k6ACgAoAKACgD+nP/AIIweGBpn7N/iTxLIv77WfEc6g46xWttbov/AI8WoA/YGgAoARvumgD+dT9qW2ntP2iPHyTgqx1MuO/yyRI4/wDQ6/LcfH/aqn+I/vrgycZ8P4OUf5f/AG6R4HXmn3Q5etAH9Bn7Hn9k/wDDOPgn+yNmz7G3m7Mf6/zX8/OO/m7v/wBWK/Tcr5fqtPlP4P479r/rDivbfzf+S8vu/wDkp9NV65+dhQAUAFABQAUAFABQAUAFAHw5/wAFFPi5cfB39k7xjrGmTGHVdcjTRbJlYI2+/JSQqTn5lgErj3WgD+O6gAoAKAP3K/4J2/8ABNnRvH+h6f8AHj9oCzNxol4BNo+hvkLdx9VubruYj1ji/wCWg+ZvkwHAP6F9J0bStC0230fRLOHT7C0URw29uixRRovRURQFUDsAOKANOgBNwoAWgAoAKACgAoATcKAFoA/iU/a5z/w1H8V8/wDQ0at/6VSUAfO1ABQB+lX/AAS1+M/wx+B3x817xZ8V9ei8O6Tc+HbizinmSSQPO91ayLHiJHblY2PTHFAH74f8PGf2LM4/4WlYZ6f8e95/8YoAP+HjP7Fmcf8AC0rDPT/j3vP/AIxQAf8ADxn9izOP+FpWGen/AB73n/xigA/4eM/sWZx/wtKwz0/497z/AOMUAH/Dxn9izOP+FpWGen/Hvef/ABigA/4eM/sWZx/wtKwz0/497z/4xQB/Ob/wUZ+KHgP4v/tR6345+G2rx67od1ZadHHcxJIgLxW6I4xIqtkMCOlAHwvQAUAfff8AwS+/5Ph+HX01T/023VAH9fA6UALQAUAFABQAUAFABQAUAFABQB//1P38oAKACgAoAKACgAoAKACgAoAKAP5J/wDgq3qJvf21vF9uTkWFnpUI/Gxik/8AZ6APzjoAKACgAoAKAP60f+CT2mrY/sWeFrsfe1G91Wc/heSR/wDslAH6R0AFABQB+JH/AAUF8BXXh/4x2/jOKLFl4os4yXCkKbm1Aidc9MiPyj+P5fn2c0uSv7T+Y/sbwvzKNfKJYP7VKX/ksvej/wCTcx8HV84ftwUAew/C/wCPfxV+ECzQeAtbaztLli72sqRzW7OcZISQHaeOq4J79BXfh8ZXofw5Hymb8M5Zm/LLHUeaUftfDI9xX9vn9ofGPtmln/uHj/47Xof2zi/7v/gJ8X/xDPIP5an/AIF/9qH/AA33+0PjH23TP/BeP/jtH9s4v+7/AOAh/wAQzyD+Wp/4F/8Aah/w33+0PjH23TP/AAXj/wCO0f2zi/7v/gIf8QzyD+Wp/wCBf/ah/wAN9/tD4x9t0z/wXj/47R/bOL/u/wDgIf8AEM8g/lqf+Bf/AGof8N9/tD4x9t0z/wAF4/8AjtH9s4v+7/4CH/EM8g/lqf8AgX/2of8ADff7QvT7Xpf/AILx/wDHaP7Zxf8Ad/8AAQ/4hnkH8tT/AMC/+1Oj0X/gon8a7CT/AIm+m6NqcfcGGaF/++hLj/x2tIZ3iV8UYnm4jwsyef8ADqVI/wDb0Zf+2n0v8Of+CivgLXbiHT/iHotx4akfapuYW+2WoJOCW2qkgHsEb/D16Gd0n7taPKfnmaeFWOoxlUy+tGr/AHZe7L/5H/0k/QHw94i0PxXpNvrvhy+h1LT7tQ8U8DrJG6nuGUkGvqITjOPNE/CcVha+Gqyw+IjKMo/ZkbdUcp+GP/BbnxM9v4D+Gfg8SELqGo398yZ4zZxJEp/K4b9KAP52aACgD6T/AGP/AINxfHj9o3wT8M71C+nX96Jr7bjmytFNxOuT0LRxsoPqRQB/atZWdrp1pDYWUS29tboscUcahUREGFVQOAABgAUAW6APjf8AbX/at0L9lT4RXPiZmS58U6wJLXQrJsHzbkAbpXGQfKgDBnx1+VcguDQB/IfrvxO+IXiXWr/xHrniPULvUNSme4uJXuZS0ksh3Mxwcck80AZX/CZeMf8AoO3/AP4FS/8AxVAB/wAJl4x/6Dt//wCBUv8A8VQAf8Jl4x/6Dt//AOBUv/xVAB/wmXjH/oO3/wD4FS//ABVAB/wmXjH/AKDt/wD+BUv/AMVQB9mf8E9vFPiW9/bL+F9te6td3EL6hOGSSeR1I+xz8EE9KAP6/k+6KAP4l/2uc/8ADUfxXz/0NGrf+lUlAHztQAUAFADtzf3jQAbm/vGgA3N/eNABub+8aADc3940AG5v7xoAbQAUAFAH33/wS+/5Ph+HX01T/wBNt1QB/XwOlAC0AFABQAUAFABQAUAFABQAUAf/1f38oAKACgAoAKACgAoAKACgAoATtQB/IV/wVB3f8NwfEX6aX/6bbWgD4BoAKACgAoAcvWgD+vH/AIJd7P8Ahh74dbev/E1z9f7TuqAP0BoAKACgDw39oD4K6T8cfh7d+Ebt1tb+M/aNPumTd5F0isEJxyUO4qwHYkjkAjzsZg44ml7M+y4X4gq5JmEcVH3o/DKP80f6+E/n18ceAvFfw58TXnhHxnYPp2p2Z5Rh8rqejo3R0bswJB7GvzSrSnRn7Op8R/d2W5nhMww0cVg6nNTl/XvfyyOTrnPUCgAoAKACgAoAKACgAoAKAPov9nL9obxD8CfFsNwk0lz4YvZVXU7HO5dh4M8Y6CVRg8YDgBSRwV9TAY2php/3T4DizhWhneFlHl5a0fhl/wC2y/u/+k/Ef0GaTqdjrOmWmr6ZMtzaX0STQyr92SORQysPYggiv06MouPNE/hKrSnRnKjUjyyj7sj8Bf8AguHDN/avwhm/5Y+TrY/4FmzqjnPwWoAKAP1N/wCCPy2z/tdD7QQGTQNSaLt+83wL/wCglvzoA/qnoA4r4h+P/C/wu8E6x8QfGl4un6JoVu1zczN2QcAKOpZmIVVHLMQBkkCgD+Nb9rD9pTxT+1H8XtS+Imus9tpyk22k2DMSllZIxKIB0LsSWkbuxOMKAAAfNNABQAUAFABQAUAfan/BOrH/AA2p8Lc9P7Rn/wDSOegD+x1furQB/Ev+1zn/AIaj+K+f+ho1b/0qkoA+dqACgAoAKACgAoAKACgAoAKACgAoA++/+CX3/J8Pw6+mqf8AptuqAP6+B0oAWgAoAKACgAoAKACgAoAKACgD/9b9/KACgAoAKACgAoAKACgAoAKACgD+Sb/gq3pxsv21vF9wRxf2elTD8LGKP/2SgD85KACgAoAKACgD+tD/AIJO6mt9+xZ4XtM/Np19qsB/G8kk/wDZ6AP0koAKACgAoA82+JPwk8AfFrRv7G8e6RDqcSbvKkYbZ4CwwTFKuHQ4PO0jPeuWvh6VaPLUie9lWd5hlVX22Bqcsv8AyWX+KP2j8/fGv/BNuylmluPh74ukto3bK2+pwiXaDj/ltDsI/FD/AEr5erkcf+XdT/wI/eMu8WpqPLmGF5v70Zcv/ksv/kjxHUP+CeHxztHZbS90W9Tsy3U6foYK4JZJif7p9lS8U8lnH3o1I/8Absf/AJIzv+Hfn7QP93R//A1//jFT/Y2L/unR/wAROyL/AKef+A//AGwf8O+v2gcfd0j/AMDn/wDjFH9jYv8Auh/xE7Iv+nn/AID/APbB/wAO+v2gcfd0j/wOf/4xR/Y2L/uh/wAROyL/AKef+A//AGwf8O+v2gcfd0j/AMDn/wDjFH9jYv8Auh/xE7Iv+nn/AID/APbB/wAO+v2gcfd0j/wOf/4xR/Y2L/uh/wAROyL/AKef+A//AGxVvP2BP2hbWAzRW2mXZH/LOK+Ic/TzY40/NhUSybFo0h4m5A5cspVI/wDbv/2x8k+KPCniLwXrlz4a8V2EumanZHEtvMNrqCMgg9CrAghhkEEEEgg141SEqcuWpH3j9TweNoYyhHEYWpzU5faiYNZHaIOlAH7p/sF+MZvFHwEttKu5BJP4avJ9OHGD5Q2zRfgqyBB7LX6Jk1Xnw3L/ACn8VeJeAjhs8lUj/wAvYxl/298Mv/ST4t/4LW+DLrU/gx4G8cwRb00HWpbWVl6ol/ASGPsDAF+rV9AfkB/NnQAUAfW/7DHxis/gh+1D4H8davOLbSDdtYX7tyi21/G1s0j9PliLiQ/7tAH9nMbrIm5WDA9xQB+Vf/BQv9nP9q/9qGbTPAvwym0jTPAWmhbmdLq+limvr35wGkRIHASNDhV3HLMxOfl2gH5d/wDDnL9rXH/Hz4b/APBjN/8AItAB/wAOcv2tcf8AHz4b/wDBjN/8i0AH/DnL9rXH/Hz4b/8ABjN/8i0AH/DnL9rXH/Hz4b/8GM3/AMi0AfO37SX7Cfxr/Za8Jab4x+Js+lSWOq3osIhYXUkz+cYpJhuDxR4G2NufXtzQB8YUAFAH2p/wTqx/w2p8Lc9P7Rn/APSOegD+x1furQB/Ev8Atc5/4aj+K+f+ho1b/wBKpKAPnagAoA774d/Cz4h/FnWZ/D3w08O3viXUraE3MlvYQvPKsKsqFyqAnaGdQTjqR60Aeyf8MTftZ5/5JJ4l/wDBbP8A/EUAH/DE37Wef+SSeJf/AAWz/wDxFAB/wxN+1nn/AJJJ4l/8Fs//AMRQAf8ADE37Wef+SSeJf/BbP/8AEUAH/DE37Wef+SSeJf8AwWz/APxFAB/wxN+1nn/kkniX/wAFs/8A8RQB4Z46+H3jf4ZeIJvCnj/Rbrw/rECo72t5E0MqrIoZSVcAjIIPIoA5CgAoA++/+CX3/J8Pw6+mqf8AptuqAP6+B0oAWgAoAKACgAoAKACgAoAKACgD/9f9/KACgAoAKACgAoAKACgAoAKACgD+Xb/gsp4dk0v9qLSdbA/daz4btJM+rwXFxEf0AoA/JSgAoAKACgAoA/py/wCCMHihdT/Zw8S+GpG/faN4jncD0iura3df/Hg9AH7BUAFABQAUAFABQAUAFABQAUAFABQAUAfjP/wUeXTB8UvDTWwT7cdIPn7fv+X5z+Vn8fM/Svg885fax/wn9c+E/tf7MxHN8PtPd/8AAfe/9tPzvr5c/ewoA/Xv/gmo0p8DeM0P+rGqQY/3vsybv0xX3GQ/BU/xH8peLXL9cwv/AF7l/wClH0f+2N8G2+O/7N/jb4c2kIl1O6smuNPGMn7baETwKDxje6BCfRj9a+sP54P4rZ4JYJXgmQxvGcMpGCD6GgCOgAoA/oc/4J2f8FI/DFz4a0n4FftAaqNM1TTVitNI1u7kC291AuEjgupXIEcqDAWRjtdQAxDgFwD90YJ4bmJJ4XDpIMqwOQR6igCegAoAKACgD8Z/+C12P+Gf/BH/AGNCf+kN1QB/NHQAUAfan/BOrH/Danwtz0/tGf8A9I56AP7HV+6tAH8S/wC1zn/hqP4r5/6GjVv/AEqkoA+dqACgD9eP+CLf/Jz3ib/sVLv/ANLbKgD+nvavoKADavoKADavoKADavoKADavoKADavoKAP5Mv+Csef8Ahs/xJ6f2fpH/AKSJQB+bNABQB99/8Evv+T4fh19NU/8ATbdUAf18DpQAtABQAUAFABQAUAFABQAUAFAH/9D9/KACgAoAKACgAoAKACgAoAKACgD8CP8Agt14PPlfDDx/AOEbUdNnJBxlxHNEPT+GU/n60AfgFQAUAFABQAUAfuX/AMESfHQtPHPxH+HEsoxqmn2mqRIeoNjK0MhH1Fyn5UAf0U0AFABQAUAfJn7Vf7SEfwF8LWiaIkF54p1d9tpbzgvHHEp+eaVUdG28bVAYZJJGQjCvEzHH/Vqfu/FI/UOCuFP7cxMpVuaNGn8Uo/zfZjE/P7/h4n8cen9maF/4DXH/AMk18z/bWJ/lifu3/EKsl/5+VP8AwKP/AMiL/wAPFPjj/wBA3Qv/AAGuP/kij+2sT/LEP+IVZL/z8qf+BR/+RD/h4p8cf+gboX/gNcf/ACRR/bWJ/liH/EKsl/5+VP8AwKP/AMiH/DxT44/9A3Qv/Aa4/wDkij+2sT/LEP8AiFWS/wDPyp/4FH/5EP8Ah4p8cf8AoG6F/wCA1x/8kUf21if5Yh/xCrJf+flT/wACj/8AIh/w8U+OP/QN0L/wGuP/AJIo/trE/wAsQ/4hVkv/AD8qf+BR/wDkQ/4eKfHH/oG6F/4DXH/yRR/bWJ/liH/EKsl/5+VP/Ao//IlK/wD+ChXx5vbZ4YINFsmJBEkVpKXGP+uk7p+a1Ms7xL/lNKXhbkalzSlUl/29H/5E+OvF3jHxP478QXfinxdfyanqt6cyzSnk44CqowFUDgAAADgADgeHOrOpLmqS94/W8BgMNgaEcLhafLTj9k5ysjvCgD9sf+CeHhxtL+CV5rcykNrerTyqcYzHAkcAP/fcbivv8kp2w0pfzSP458UcVGpnEaMf+XdOP/k3NL/24+96+lPxE/lb/wCCpX7KV38F/jBcfFfwxZlfBvj64ecsoGy01N8vcQkADAlO6WP6uoGEyQD8r6ACgAoA+nfg/wDtk/tJ/A23i074c+Or6y0yEnbYXGy8s1BxkJDcLIkecZOwKSetAH13p/8AwWK/ays7cQzW3hu8IJIkn06cOR6ZiuY1/JBQBf8A+Hy/7VuP+QV4V/8AAG6/+TKAD/h8v+1bj/kFeFf/AABuv/kygA/4fL/tW4/5BXhX/wAAbr/5MoA+bv2mP28vjL+1T4R0zwZ8SrHR7ax0q/F/C+m208MplWKSEBmlnlBXbI3AA5xzxQB8U0AFAH2p/wAE6sf8NqfC3PT+0Z//AEjnoA/sdX7q0AfxL/tc5/4aj+K+f+ho1b/0qkoA+dqACgD9ev8Agi5/yc94n/7FS7/9LbKgD+nqgAoAKACgAoAKAP5Mf+Csef8Ahs/xJ6f2fpH/AKSJQB+bNABQB99/8Evv+T4fh19NU/8ATbdUAf18DpQAtABQAUAFABQAUAFABQAUAFAH/9H9/KACgAoAKACgAoAKACgAoAKACgD81P8AgrB8PG8c/sga1q1vEJrnwhf2WroP4toc2suPpHcMx+lAH8m1ABQAUAFABQB9vf8ABOn4mp8Lv2vPAup3kqxWOtXD6Nc7jtUjUFMMWTg4CzmNz/u0Af2KjpQAtABQBy3jTxbongTwtqfi/wASz/ZtM0qFp5nxlsL0VR3djhVHdiAOTWVWrGnCVSXwno4DBV8biaeDw8eapKXKfzlfF/4oa78X/H+p+OddPlvduUt4QSVt7ZSfKiXP90Hk8bmJbAJNflWIxEq9WVSR/oBkOTUMpwNPA0fs/FL+aX2pf19k81rlPowoAKACgAoAKACgAoAKACgDb8MeHNZ8X+IdP8MeHoDc6jqcyQW8Y6Fyckk9goySegAJPANawhKcuWJxYzGUsJQqYrES5acY80j+k/4YeBrD4a+ANC8DacS8OjWscBcnPmSAZkf6u+WPua/VcPQjRpRpx+yf56ZvmVTMsdWx1T4qkuY76uo8M8x+Lvwl8E/G34f6t8NPiDYjUNG1iIxyLna8bDlJYmH3ZI2AZDzhgDg4xQB/Ih+1v+yD8Rv2UvHUmieJYm1Dw3fyMdJ1iNCIbuPqFf8AuTqPvoTweQWUhiAfJFABQAUAFABQAUAFABQAUAFAH2p/wTqx/wANqfC3PT+0Z/8A0jnoA/sdX7q0AfxL/tc5/wCGo/ivn/oaNW/9KpKAPnagAoA/Xr/gi5/yc94n/wCxUu//AEtsqAP6eqACgAoAKACgAoA/kx/4Kx5/4bP8Sen9n6R/6SJQB+bNABQB99/8Evv+T4fh19NU/wDTbdUAf18DpQAtABQAUAFABQAUAFABQAUAFAH/0v38oAKACgAoAKACgAoAKACgAoAKAOE+Jvgew+Jfw78S/D7VNv2TxHp11p8hYbtq3MTRFseo3ZHuKAP4YfEeg6j4X8Qan4Z1mLydQ0m6mtLhP7k1u5jkX8GUigDEoAKACgAoAuaZf3mlX9vqenym3urWRJYpFOCrodysPcEAigD+4L9nv4qWXxr+Cng74pWRU/8ACQ6dDPMq4xHcgbLiPgnPlzK6ZzztzQB7NQAhOKAPxh/bu+Pg8Z+J/wDhUvhm4DaN4elJv5FyBcX64Plc8FYMYP8AtkgjKA18Hm+N9rU9jH4Y/wDpR/XPhtwz9Tw39rYqP7yp8P8Adj/9t/6SfntXy5+9hQAUAFABQAUAFABQAUAIOlAHZ+B/h940+JOrpoXgbSJ9YvGOGEK/JH7yOflRf9piB6muilQnWly048x5GY5pg8vpe2x1SNOP97/22PxSP2h/ZZ/ZO0z4JW58V+J3j1PxjexBGkXJhskYfNFDkAljnDOQCR8oAGS/3mXZbHD/ALyp8R/H/GXG9TOZfVcL7uHj/wCBS/vS/wDbYn2oOlfQH5ELQAUAcJ8RPhr4G+LHhO+8D/EPRrfXdE1BSJba4XIJ7MrDDI69VdSGU4KkEA0Afz4ftPf8EgfHvhO4u/FH7Od0fFWjMXkOkXbpFqVuOTtilO2K4UAd/LccABzk0Afjz4r8GeLfAmszeHvGej3mhanAcSW17A9vMuPVJArD8RQBzu2gBtABQAUAFABQAUAFAH2p/wAE6sf8NqfC3PT+0Z//AEjnoA/sdX7q0AfxL/tc5/4aj+K+f+ho1b/0qkoA+dqACgD9ev8Agi5/yc94n/7FS7/9LbKgD+nqgAoAKACgAoAKAP5Mf+Csef8Ahs/xJ6f2fpH/AKSJQB+bNABQB99/8Evv+T4fh19NU/8ATbdUAf18DpQAtABQAUAFABQAUAFABQAUAFAH/9P9/KACgAoAKACgAoAKACgAoAKACgBO1AH8nP8AwVY+DD/C/wDam1HxPYwiPSfiBCurxFSMC5J2Xa8YO4yDzTnp5oFAH5pUAFABQAUAFAH9Cv8AwRg+PMV5oHij9nnWrgfadOc61pQYjm3lKx3US9DhJCjgc5MjH1wAfu/QBk63YXOp6Re6daXkunTXMMkSXMOPNhZ1IDpuBG5c5GQealxvHlN8PVjTqxqSjzcv2ZfaPghv+CcfwnZi7+I9dZickmW2JJ9T/o9fM/2HQ/mkfuP/ABFfNV8NGn/4DL/5Ib/w7f8AhL/0MOt/9/Lb/wCMUf2HQ/mkX/xFfNf+fNP/AMm/+SD/AIdv/CX/AKGHW/8Av5bf/GKP7DofzSD/AIivmv8Az5p/+Tf/ACQf8O3/AIS/9DDrf/fy2/8AjFH9h0P5pB/xFfNf+fNP/wAm/wDkg/4dv/CX/oYdb/7+W3/xij+w6H80g/4ivmv/AD5p/wDk3/yQf8O3/hL/ANDDrf8A38tv/jFH9h0P5pB/xFfNf+fNP/yb/wCSD/h2/wDCX/oYdb/7+W3/AMYo/sOh/NIP+Ir5r/z5p/8Ak3/yQf8ADt/4S/8AQw63/wB/Lb/4xR/YdD+aQf8AEV81/wCfNP8A8m/+SD/h2/8ACX/oYdb/AO/lt/8AGKP7DofzSD/iK+a/8+af/k3/AMkWrP8A4Jy/BmJt11rWuXA9PPt0/lb1ccjofzSMp+Kubv4aNP8A8Bl/8keleG/2Hf2dvD0gml0CTWJRwG1C6lmGMY5jDLEf++K6YZThIfZ5j5zFeInEGI92Nb2f+GMY/wD2x9PaD4a8P+FtPTSvDmm2+mWafdhtolijH0VAB+levCEYR5YxPznEYqviantMRUlKX96XMbtanEFABQAUAFABQBwvjj4Z/D34l6adI+IPhvT/ABHZ4IEWoWsVyoz3USqwB9xzQB8Q+Mf+CWH7G/i2WS4tvClz4eml+82mX9xGPwjmeWIf98UAeOXn/BGD9mOaQta+IfFEKnt9rsz/AO2dAFf/AIcufs1f9DP4o/8AAmz/APkWgA/4cufs1f8AQz+KP/Amz/8AkWgA/wCHLn7NX/Qz+KP/AAJs/wD5FoAP+HLn7NX/AEM/ij/wJs//AJFoAP8Ahy5+zV/0M/ij/wACbP8A+RaAD/hy5+zV/wBDP4o/8CbP/wCRaAPUPgx/wS0+BXwQ+J+g/Ffwtr2v3Oq+H5nngiu57Z7djJG8R3Klujfdc/xUAfpkOlAH5X/EX/gkp+z/APEvx94i+Ieu+IvEUOoeJb+41CeO3uLVYUkuZGkcIHtnfG5j1Yn3oA43/hy5+zV/0M/ij/wJs/8A5FoAP+HLn7NX/Qz+KP8AwJs//kWgD6P/AGYP+CfPwk/ZT8e33xB8BaxrGoX9/p8mnPHqEtvJEsUkscrFRHBGwbdEvO48Z45oA+9KACgAoAKACgAoA/Or9ob/AIJrfBf9pH4oX/xV8Z65rllqd/DbQNDZTWyW4FrGI1IElvI2SoGfmxkUAeI/8OXP2av+hn8Uf+BNn/8AItAB/wAOXP2av+hn8Uf+BNn/APItAHr3wH/4JifBL9nv4q6L8XPB+u69eatonn+VFez2z25+0QPbvlY7dG+5I2PmoA/SQdKAFoAKACgAoAKACgAoAKACgAoA/9T9/KACgAoAKACgAoAKACgAoAKACgAoA/Mn/gqn8A3+MP7Nt14s0a3M2vfD2RtWhCgs7WQXbeIAAeBHiY+vlAdcUAfyg0AFABQAUAFAHsv7Pnxj134B/GDw18V9BLPNoV0sk0KsVFxbMClxAcEcSRMy57Eg4yBQB/bJ4J8YaB8QfCOj+N/C10t7pOt2sN5ayoQQ0UyB1zjocEZB5B4IyMUAdXQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB//1f38oAKACgAoAKACgAoAKACgAoAKACgCteWlvfWs1ldxrNBcI0ciMMq6OMMpHQgjg0Afxk/trfs73v7Nfx/17wKkLpoV651DRZGBIawuWYou4gbjEytET3KZ7igD5KoAKACgAoAKAP33/wCCP/7V6Itx+y541vcZMt54cklf6y3NmoP/AAKaPH/TTJ+4KAP38BzQAtABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfC/7QX7bPh74OeKk8F+HNLTxNqdum6+xceRHalshI9wjkzIcbmXjA29d3HzmNzaOHn7OMeaR+z8L+H1fNsLLGYip7KnL4fd5ub+9/hPA/+Hl2qdP+EBi/8GJ/+MV539vS/wCff/kx9z/xCOl/0Gf+U/8A7YZ/w8v1X/oQYv8AwYn/AOR6P7el/wA+/wDyYP8AiEdL/oM/8p//AGwf8PL9V/6EGL/wYn/5Ho/t6X/Pv/yYP+IR0v8AoM/8p/8A2wf8PL9V/wChBi/8GJ/+R6P7el/z7/8AJg/4hHS/6DP/ACn/APbHdfDX9urxp8U/G+meBvDXw9he71GQAyHUXKQxLzJK+Lfoqgt7kBRyRW9DN51pxpxp/wDkx42b+G+Dy3B1MdiMd7sf+nfxS+zH4vtH6W19afzwFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB/9b9/KACgAoAKACgAoAKACgAoAKACgAoAKAPzj/4KT/srH9ov4JS614Ys/P8a+CRNfacEA8y5g2f6Ta5PJMgVWQDkuijgMTQB/JSy7SytQA2gAoAKACgDb8NeI9b8IeINO8U+GryTTtV0m4jubW5iO14pYmDo6nsVYAg+tAH9iP7FH7Vvh/9qv4R2/iWJ0t/FWkBLbXLJcAxXOCFlRcn91OFLoeccpklDQB9kUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAJkUAfBf7Wn7Wth8LrG48BeAbhLvxjcpiWZcPHpsbfxN2Mp/gTt95+Nqv8AOZlmXsY+zp/F/wCkn7dwRwRUzOpHHY6PLh4/+VP/ALX+aX/bsT8U7q5uL24mvbyV5p7h2eSSRizuznczMW5JJOSTya/PpSuf2HCEYR5Y/CQUFhQAUAS2ttcXtxDaWkbTTzuscccYLO7udqqoHJJJwAOtESJTjCMpS+E/dz9kP9nGL4K+ETrniGMN4w16NWvDjP2WEnKWqHJHy8GQj7z9yqoR+jZbgvq9Pml8Uj+JeOOK5Zxi/Y4f/d6fw/3pfzf/ACP90+x694/KAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAP//X/fygAoAKACgAoAKACgAoAKACgAoAKACgBO1AH8v/APwVM/Y5l+EHj2T44eA7I/8ACG+MbhmvIoUxHp2pylncfLwIp8F17Bt68DYCAfkZQAUAFABQAUAfQn7M37Rnjn9mP4paf8RvBkpkjH7nULFmAjvrJz+8gfIODwGRsHa6q2DjBAP7FPgl8aPA/wAfPhzpfxM+H94LrTNRX50PEttOoHmQTLk7ZI88joQQykoysQD1ygAoAKACgAoAKACgAoAKACgAoAKACgAoAhkkjiRpJGCqoySegFARjf4T8yf2mf25LLSo7zwJ8FLhLvUHBiudaXDQwAjkW2QVkfB/1nKKPu5JynyWPze37vD/APgR/RnCHhzUqcuOziPLH7NP7Uv8X8sf7vxf4T8mri5ub2eW6u5nnnmZnkklYu7uxyzMzZJJPJJr4g/qWEIwjyxj7pBQWFABQA5V3HavzN6UAfsH+xr+yYfBqW3xY+JdljX5Ru02xlXIsUYEGWRT/wAt2BIC/wAAyT85wn3WV5d7P99W+L7J/JvH3G/1zmyvLZfuftS/m/ux/u/+lf4fi/SIDFfVH8+i0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB//0P38oAKACgAoAKACgAoAKACgAoAKACgAoAKAOI+Ivw+8K/FTwTrHw+8bWK6jomt27W9zC3dTyGU9VZWAZWGCrAMCCAaAP47P2u/2WfFn7KvxVufBOtGS+0W7Lz6PqZTal7aZ4BxwJYwQsqjoSCBtZCQD5VoAKACgAoAKAPsH9j39sHx3+yX4+OtaOX1PwvqhRNX0hnwlyg6On9yePkq+OOQcqSCAf1ufBz4y/D347eA7H4ifDXVE1PSb0YYcCa3lAG6CePJMcqZGQeCCGUsjKxAOxl8WaHa67F4bvblbbULlS1ukv7v7QFxuETNgOyg5ZVJIHJAHNZe1jzcp3xwVd0JYinHmjH4v7v8Ai/lOlBzWpwC0AFABQAUAFABQAUAFABQAh6UAeG/Fz9of4XfBizZvF2qq2osuYtPtiJbyTp0jB+UHP3n2r2zmvOxGNpYf+JI+yyPhXM84l/stP3f5pe7H/wAC/wDkT8ffj1+178Q/jOZ9EsmPh3wtKCv2C3cmSdM5/wBJl43gjHyAKvqGIBr4XGZnVr+78MT+r+GeBcvyflrS/eVv5pfZ/wAMfs/4viPkyvGP1MKACgAoAtafYXuq30GmaZbSXl3csI4oYlLvI7cBVVckk+gFEY392JlVqwpwlUqS5YxP2G/ZQ/Y0t/ArW3xF+K1tHc+JARJZ2Bw8WnnAIdzkiScHkEDah5XcQHH3WW5X7P8AfVviP5N414+ljebL8rly0ftS+1L/AORj/wClH6LjpX1R+BC0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAf/9H9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoA+e/2kv2cvh9+038Nbz4eePINpbE1jeooNxY3ag7J4+R7qy5AZSy5GcgA/kC/aE/Z8+If7N3xFvvh18Q7Ty7iL95a3SA/Z722JISeBiPmVsH3BBVgGBAAPDKACgAoAKACgD6O/Zp/ai+KP7L3jZPFvw+vt1pOyLqGmTEtZ30IP3XUEEOOSjqQynIyVLKwB/UX8C/2j/gB+3N8PJ9OtUja/iRX1LQbx1F9ZSL0liIwzKrYMc8eMHH3Hyo56tKFSPLUPSwGPxOArxxGFqcsv6/8l/unPeMW/aZ/ZyL6r4TuH+KfgSH5ja3+6TV7CP8Au+dF+8mjRf8Alptkb+8v8VeDV+uYT3qf7yn/AOTH6/gP9XOIf3eKj9UxP80f4cv+3fhj/h93/Ea/gD9vr4KeK0SHxO9z4TvCDlbyPzbckf3Z4dwxju6p/hdDOcNP4vdOXNPDLOMJ72H5asf7vxf+Ay/+2Pr7w54y8J+MLUXvhXWbTV4WGd9rOk68+6EivehVhP3qcuY/KcVgMVhJezxVOVOX96PKdNkVqecLQAUAFACbl9aAMDXvFPhvwvam98S6ra6TbqMmS7nSBP8AvpyB+tZTnTh8Ujtw+DxOJl7PD05Sl/djzHyT4+/bw+BnhBJINDvZvFV8B8senxExbjjGZ5NkZGO6Fq8Orm+Gh8PvH6llfhtnWK96tGNKP974v/AY+8fAvxR/bu+MHjoSWHhh4/B2mPkYsyXvGGcjdcN93p1jRCPX1+dr5vXqe7H3T9zybw2yjBfvMV+9l/e+H/wH/wCS5j4uuru5vbqS8vZnubic7nklYu7H1ZmySfUmvnua5+vwhGEeWMeWJBQWFABQAUAeqfCn4L/ED4y60NG8DaaZ0RgtxdyER2tuMZ3O5/RVDMewODXbh8LVry5acT5nO+IMvyeh7bHVOX+WP2pf4Y/1E/av9nz9lXwP8DLePVdo1rxTLHtm1GVAPL3AbkgQk+UvbIO5h1OMKPvsFl1LDe98Uj+POKONMdncvZ/w6P8AL/8AJfzf+kn1Oqheleyfmg6gAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA//S/fygAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD5w/aX/Zk+HP7UHw/n8EePbYJPEGk07UYlH2qwnx99DxuRsASRk4YejBWUA/kj/aT/Zj+J/7MPjubwb8QrLNvKztp+owgmzv4FP34mIGGAI3owDKSMjBUkA+dqACgAoAKACgDp/B3jPxX8PvEdj4t8FarcaLrGnSCW3urWRopY2HoykHB6EdCCQcgkUAfv7+yb/wV20HXYrTwT+07GukamAI08QWseLOds4BuoQcwMR1dAYyc5WIDJAPvz4o/sq/Bb9oPTh438H3cGmalqamaHV9JMctvdl8fvJUU+XMCB94MrH+/ivDxWV0q/vR92R+p8PcfZnlPLRqfvaP8svs/4ZfZ/wDST8wfid+y/wDGv4KXc2qy2Et3p0JJXVNIaR0VBgbpNoWSLGeSRtH97PFfHV8uxOGlzcv/AG9E/p3JuMMnzqPsYy5Zf8+6n9csjlNA/aQ+O3hxEXSPHeqGOI8LNMbtfyn8wVzwx+Jh8NSR6mK4SyOv/GwdP/wHl/8ASeU9Ssv26f2j7RQk2uWt2RjmbT4B/wCiRGf1rtWb4pfa/wDJT5mfhvw9P4aMo/4ZS/8Atjc/4b//AGgfL2edpOfX7C//AMfrX+2cX/dOP/iGOQ/9PP8AwL/7Uxrv9uz9o+5UpDrdnaE94dPhP/o0SH9TWUs4xf8AMdVLw34eh8VGUv8At6R5jr37TPx88QiRdT8damiy4DLbSLaDj/r3EdcssfiX8VSR9HheEMjofw8HT/7e97/0rmPGb/Ub/VLg3erXUt7cNz5lxI0rn6sxJP51wSlzfEfYUqUKceWnHlj/AHfdKdQahQAUAFABQB1/gv4f+M/iHqq6N4I0a51q7ySy28ZKIB3kk+4g92IHvW9KhUqS5aceY8rH5pg8BS9tjK0acf739e8fpP8ABr/gnlFE0Os/GvUPO24I0mwche4xNP1PbIjxjqHr6vC5J9rES/7dP55z7xT5uajk9P8A7iS/9tj/APJf+An6T+DtE8KeHtAtNK8FWdrYaRAu2GKzRUhA9goAP1r62EKcI8tOJ/OeKxdfFVZYjFVJSlL7Ujq61OIKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/9P9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgDyz4vfBv4e/HLwVfeAPiXpEWraTeKcBsrLDKQQJYZAQyOueGUjjIOQSCAfy7/tkf8E6vib+zNeXXirw0s3i34eZ3rqMSZuLIEkCO+jUDBHQSqNjHGRGzBKAPzmoAKACgAoAKACgD6O+An7WXxz/Zv1H7T8L/ABHNa2Ltun0y4Jn0+c4I+eBuA3P302vjgMBQB+5vwC/4LFfCTxolvovx00mXwRqh2q17bK95pkhJxkhczxZyMKUkA6l6APtTUfgp+yv+0vpJ8W+FjpupfacMdU8PXMaOTnJ8wwlkZucHzFJH04rya+XYat8UfeP0HKONc6y2MY0a3NT/AJZe9H/5KP8A27I+SfHP/BN/xPZM9z8OvFFvqMWMi31GNreQEdvOj3hif9xRXz1XI5r+HI/act8WMNP3cww8o/3o+9/5LI+U/Fn7LHx/8INJ/afgy8u40GfNsAt4hH0gZ3791rw55diYfFTP1DBcaZDjP4eKjH/F7v8A6UeG6hpep6RK0OsWU9hKOqXETwsPwkANcElKPxH2tKvTrR5qMoy/w+8ZqyRt911P0NSb2JdtBI35V+8QtACRkStsiIdj2U5NApafEek+Gvg98VfF5B8NeEdV1BCMiRbR1iIxn/WyBU/8erqhha9T+HGR8/jM+yzC/wC8YqnH/t6P/pJ9N+C/+Cf3xv8AERSTxG1j4YtiAx+0TfaJ8H0SDeh+jSL+FevSybEz+L3T85x/idktD3cPzVZf3Y8sf/Apf/In2L4J/YJ+Cnga3/tv4g6hP4le0AkkkunFlYoEHLGONsgdyHlYf092hk1CHvVPePyDNPFDN8T7uDjGlH/wKX/gUv8A5E5b4hf8FCP2V/gcsXw8+EkC+OdfdxBaaL4TtxJC87EIqCaJfJJZuP3XmPn+AmvoYQjCPLGJ+O4jFV8TOVbEVJSl/NL3j0X4b+Bv2gfjg0fi/wDaZkTwj4cm2y2ngfSZW+df4TrN5/rJ2/6do2WH/nqrfdrU4z7ctra3s7eO1tY1hhiUIiIMKqqMAADgACgCxQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB/9T9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAguLeC7gktrqNZYpVKujDcrK3BBB4IIoA/Gv8Aaz/4JK+B/iI1743/AGe5IPB/iF8ySaS4YaVckDpFtybVj6IGj6AInLUAfz5/FX4NfE74J+JpfCHxR8PXXh/U4yQq3Cfu5R/fhlXMcqdt8bMpOcE4oA8yoAKACgAoAKACgDqvB/jvxr8PtWTXfAuu3vh/UU6XFhcyW0w+jxspH4GgD9Dfhf8A8FZf2r/AKw2fiK+0/wAbWEeRt1W2xMFJzxPbtC7MPVy5oA+9PAf/AAWy8AXkcMPxK+Heo6VIDtkl0u6hvVP+1sm+ylR7bm+tAH1JoX/BUP8AYk8ZwJb6z4jm0wydItU0u4wPq0aSxj/vupkoy+I1hVnTlzU5cp1MX7Qn/BOjxYu6bxH4FnaTvdRWsDf+R40auV4Wg/ipx/8AAT3KWfZrS/h4qpH/ALel/wDJFhde/wCCcV0vnDW/h0w/6/dOX/2pWX1DCf8APuJ6MeLc+j/zGVP/AAKRXf4qf8E4PD37xdf+Hy7f7j2M7f8Aju+qjg8NH4acf/ATnnxLnU/ixlT/AMCkY17+37+wH8P4W/srxbpm+LOItK0u4c5J6L5dvsH511RpU4fDE8SvjcVW/jVpS/xSkeEeNf8Ags9+z5ogeHwZ4Y17xHOvIaRIbK2PHQO8jyj8YfyrU4D4f+JP/BZr49eIhJbfDjw5pHg6F84lkD6jdIMYGHkCQ++DC319ADyz4cfBz9ub/goLqUep+K9f1SbwiXJk1TVpHh0pDuBb7LarsSV/aFNoIw7JnNAH71fssfsMfBf9lmwivPDll/bfixoylxrl6itcEOclYF6QJjjCZYjAd3wMAH2rQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH/9X9/KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgDz74jfCz4efFzw5N4S+JegWniHSZSCYbuMOEYHho24aNx2dCGHYigD8Uv2g/+CMlhObvxB+zj4i+ytguNF1hmePjHyw3aKXA67VkRieploA/Gb4u/s4/Gv4F6g1h8VfCN9oShii3DxeZZyEHBEd1Hugc/7jmgDxKgAoAKACgAoAKACgBy9aAELM33moAT8BQAo+X7tAD1WSQqvLM3Cj1oA+4fgV/wTv8A2nvjq9ve6Z4Zfw3oUpVjqWtg2cJQnG6OMgzSg84KRlTj7w60AfuD+zp/wSi+Anwie18QfEXd8RfEUO1wb6JU02Jxg/JZ5cPzkHzmlB6gKaAP1EtbO1sbeO0s4lggiUIiIAqqq8AADgACgC1QAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB//W/fygAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgDP1PTNO1ixn03V7WK9tLhdkkM6CSN1PZlYEEfWgD4H+LX/BMb9kr4qGa7h8Mt4P1GXcftOgyCzALHPFuyyWw59IgffrQB+bvxI/4IneN7EyXXwo+IFjqseNy22r28lm4PHHnQ+cHPv5aD+VAHxD43/4JrftkeCJHaXwBNrNuPuy6VPDegnGcCJHM3/kP8qAPl7xH8F/i54NeRfF/gvWtF8r7xvNOuLdf++nQCgDziWGSF/LmQoV7P8AK1ADM+4/OgAz7j86ALtjpepalKIdOtZbp24CxIzt+Sg0Ae2+Ev2Wf2jfHEgTwv8ADXxBfIeko024WD/v66BPyagD628A/wDBJn9rzxkYpda0jTvCNvLzv1S+jZgvqEtPtJB9m20Afefwv/4Io+CbB4r34v8Ajy81dlbc1ppECWcfH8Jmm813B9kQ/TpQB+mfwf8A2OP2bvgaIZvh74HsLW/gAxf3KfbL0EHORcTl3TPcKQPbrQB9OAYoAWgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAP//X/fygAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgBMCgA2igDmdQ8F+ENV3HVtEsr7f1+0W0Uuf++1NAHMS/BT4OTndP4E0GQ+raXaH+cdAE9t8IPhPZP5ln4M0W3b1j022X+UdAHZafouj6UNul2MFoP+mMax/+ggUAamBQAtABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH//0P38oAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD/0f38oAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD/0v38oAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD/0/38oAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD/2Q=="

// ─── Fraction Popover Input ───────────────────────────────────────────────────

function FractionInput({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  const [open, setOpen] = useState(false)
  const p = value ? value.split("/") : ["", ""]
  const [num, setNum] = useState(p[0] || "")
  const [den, setDen] = useState(p[1] || "")
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const q = value ? value.split("/") : ["", ""]
    setNum(q[0] || "")
    setDen(q[1] || "")
  }, [value])

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener("mousedown", handler)
    return () => document.removeEventListener("mousedown", handler)
  }, [])

  const emit = (n: string, d: string) => {
    if (n && d) onChange(`${n}/${d}`)
    else onChange("")
  }
  const handleNum = (v: string) => { setNum(v); emit(v, den) }
  const handleDen = (v: string) => { setDen(v); emit(num, v) }

  return (
    <div ref={ref} className="relative">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className={`border rounded px-1.5 py-1 text-xs w-12 text-center focus:outline-none focus:ring-1 focus:ring-[#C62828] transition-colors
          ${open ? "border-[#C62828] bg-red-50" : "border-gray-300 bg-white hover:border-gray-400"}
          ${value ? "font-semibold text-gray-800" : "text-gray-400"}`}
      >
        {value || "—"}
      </button>
      {open && (
        <div className="absolute z-50 top-full left-0 mt-1 bg-white border border-gray-200 rounded-xl shadow-xl p-3 w-24 flex flex-col items-center gap-1">
          <p className="text-[9px] text-gray-400 font-medium uppercase tracking-wide">Fraction</p>
          <input
            autoFocus
            type="text"
            inputMode="numeric"
            value={num}
            onChange={(e) => handleNum(e.target.value.replace(/\D/g, ""))}
            placeholder="1"
            className="w-14 text-center border border-gray-300 rounded text-sm font-bold py-1 focus:outline-none focus:ring-1 focus:ring-[#C62828]"
          />
          <div className="w-14 border-t-2 border-gray-700" />
          <input
            type="text"
            inputMode="numeric"
            value={den}
            onChange={(e) => handleDen(e.target.value.replace(/\D/g, ""))}
            placeholder="2"
            className="w-14 text-center border border-gray-300 rounded text-sm font-bold py-1 focus:outline-none focus:ring-1 focus:ring-[#C62828]"
          />
          <button
            onClick={() => { setNum(""); setDen(""); onChange(""); setOpen(false) }}
            className="mt-1 text-[9px] text-red-400 hover:text-red-600"
          >
            clear
          </button>
        </div>
      )}
    </div>
  )
}

// ─── Description helpers ──────────────────────────────────────────────────────

const UNIT_OPTIONS = ["", "in", "ft", "mm", "cm", "m", "Ft", '"', "'"]

interface DescParts {
  w1: string; f1: string; unit: string; w2: string; f2: string; count: string
}

function buildDescString(p: DescParts) {
  const d1 = p.w1 + (p.f1 ? ` ${p.f1}` : "")
  const d2 = p.w2 + (p.f2 ? ` ${p.f2}` : "")
  const u = p.unit || ""
  const cnt = p.count ? ` - ${p.count}no` : ""
  if (!d1 && !d2) return ""
  if (!p.w2 && !p.f2) return `${d1}${u}${cnt}`
  return `${d1}${u} x ${d2}${u}${cnt}`
}

function parseDescString(desc: string): DescParts {
  const parts: DescParts = { w1: "", f1: "", unit: "in", w2: "", f2: "", count: "" }
  if (!desc) return parts
  const m = desc.match(/^(\d+)?\s*(\d+\/\d+)?([a-zA-Z"']*)\s*x\s*(\d+)?\s*(\d+\/\d+)?([a-zA-Z"']*)?(?:\s*-\s*(\d+)no)?/i)
  if (m) {
    parts.w1 = m[1] || ""; parts.f1 = m[2] || ""; parts.unit = m[3] || ""
    parts.w2 = m[4] || ""; parts.f2 = m[5] || ""; parts.count = m[7] || ""
  } else {
    const s = desc.match(/^(\d+)?\s*(\d+\/\d+)?([a-zA-Z"']*)(?:\s*-\s*(\d+)no)?/i)
    if (s) {
      parts.w1 = s[1] || ""; parts.f1 = s[2] || ""; parts.unit = s[3] || ""; parts.count = s[4] || ""
    }
  }
  return parts
}

// ─── PDF Description renderer ─────────────────────────────────────────────────

function renderDescHTML(desc: string, showCount = true): string {
  if (!desc) return `<span style="color:#9ca3af;font-style:italic;font-size:11px;">No description</span>`

  const parts = parseDescString(desc)

  const renderDim = (whole: string, frac: string, unit: string) => {
    let html = ""
    if (whole) html += `<span style="font-weight:700;color:#1f2937;font-size:13px;">${whole}</span>`
    if (frac) html += `<span style="font-weight:600;color:#6b7280;font-size:12px;margin:0 2px;"> ${frac} </span>`
    if (unit) html += `<span style="font-weight:700;color:#1f2937;font-size:13px;"> ${unit}</span>`
    return html
  }

  const hasD1 = parts.w1 || parts.f1
  const hasD2 = parts.w2 || parts.f2

  if (!hasD1 && !hasD2) {
    return `<span style="font-weight:700;color:#1f2937;font-size:13px;">${desc}</span>`
  }

  let html = ""
  if (hasD1) html += renderDim(parts.w1, parts.f1, parts.unit)
  if (hasD2) {
    html += `<span style="color:#6b7280;font-weight:700;font-size:13px;margin:0 6px;">×</span>`
    html += renderDim(parts.w2, parts.f2, parts.unit)
  }
  if (showCount && parts.count) {
    html += `<span style="color:#9ca3af;font-size:13px;margin:0 5px;">—</span>`
    html += `<span style="font-weight:700;color:#1f2937;font-size:13px;">${parts.count}</span>`
    html += `<span style="font-size:10px;font-weight:500;color:#6b7280;margin-left:2px;">No</span>`
  }
  return html
}

// ─── Visual Fraction ──────────────────────────────────────────────────────────

function VisualFraction({ frac }: { frac: string }) {
  if (!frac) return null
  const [num, den] = frac.split("/")
  if (!num || !den) return null
  return (
    <span className="inline-flex flex-col items-center justify-center leading-none bg-gray-100 rounded px-1 py-0.5 mx-1 border border-gray-200">
      <span className="text-[10px] font-bold text-gray-700">{num}</span>
      <span className="w-full h-px bg-gray-400" />
      <span className="text-[10px] font-bold text-gray-700">{den}</span>
    </span>
  )
}

function DescDisplay({ desc, showCount = true }: { desc: string; showCount?: boolean }) {
  if (!desc) return <span className="text-gray-400 italic text-xs">No description</span>
  const parts = parseDescString(desc)
  const hasD1 = parts.w1 || parts.f1
  const hasD2 = parts.w2 || parts.f2
  if (!hasD1 && !hasD2) return <span className="font-semibold text-gray-800 text-sm">{desc}</span>
  return (
    <span className="inline-flex items-center gap-3 flex-wrap">
      {hasD1 && (
        <span className="inline-flex items-center">
          {parts.w1 && <span className="font-bold text-gray-800 text-sm">{parts.w1}</span>}
          <VisualFraction frac={parts.f1} />
          {parts.unit && <span className="text-[10px] font-medium text-gray-500 uppercase ml-0.5">{parts.unit}</span>}
        </span>
      )}
      {hasD2 && (
        <>
          <span className="text-gray-400 font-bold text-sm">×</span>
          <span className="inline-flex items-center">
            {parts.w2 && <span className="font-bold text-gray-800 text-sm">{parts.w2}</span>}
            <VisualFraction frac={parts.f2} />
            {parts.unit && <span className="text-[10px] font-medium text-gray-500 uppercase ml-0.5">{parts.unit}</span>}
          </span>
        </>
      )}
      {showCount && parts.count && (
        <span className="inline-flex items-center ml-2">
          <span className="text-gray-400 text-sm mr-2">—</span>
          <span className="font-bold text-gray-800 text-sm">{parts.count}</span>
          <span className="ml-1 text-[10px] font-medium text-gray-500">No</span>
        </span>
      )}
    </span>
  )
}

function DescEditor({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  const [parts, setParts] = useState(() => parseDescString(value))
  const update = (key: keyof DescParts, val: string) => {
    const next = { ...parts, [key]: val }
    setParts(next)
    onChange(buildDescString(next))
  }
  const inCls = "border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-[#C62828] text-xs px-1.5 py-1 bg-white"
  const lbl = "text-[10px] font-medium text-gray-500 text-center block mb-0.5"
  return (
    <div className="space-y-2">
      <div className="flex items-end gap-1 flex-wrap">
        <div>
          <span className={lbl}>Whole</span>
          <input className={inCls} style={{ width: 42 }} value={parts.w1} onChange={(e) => update("w1", e.target.value)} placeholder="12" />
        </div>
        <div>
          <span className={lbl}>Frac</span>
          <FractionInput value={parts.f1} onChange={(v) => update("f1", v)} />
        </div>
        <div>
          <span className={lbl}>Unit</span>
          <select className={inCls} style={{ width: 52 }} value={parts.unit} onChange={(e) => update("unit", e.target.value)}>
            {UNIT_OPTIONS.map((u) => <option key={u} value={u}>{u || "—"}</option>)}
          </select>
        </div>
        <div className="pb-1 px-0.5">
          <span className={lbl}>&nbsp;</span>
          <span className="text-xs font-bold text-gray-500">×</span>
        </div>
        <div>
          <span className={lbl}>Whole</span>
          <input className={inCls} style={{ width: 42 }} value={parts.w2} onChange={(e) => update("w2", e.target.value)} placeholder="20" />
        </div>
        <div>
          <span className={lbl}>Frac</span>
          <FractionInput value={parts.f2} onChange={(v) => update("f2", v)} />
        </div>
        <div className="pb-1 px-0.5">
          <span className={lbl}>&nbsp;</span>
          <span className="text-xs font-bold text-gray-500">—</span>
        </div>
        <div>
          <span className={lbl}>Count</span>
          <input className={inCls} style={{ width: 38 }} value={parts.count} onChange={(e) => update("count", e.target.value)} placeholder="2" />
        </div>
        <div className="pb-1">
          <span className={lbl}>&nbsp;</span>
          <span className="text-xs font-semibold text-gray-500">No</span>
        </div>
      </div>
      {buildDescString(parts) && (
        <p className="text-[10px] text-gray-400 italic">
          Preview: <span className="font-semibold text-gray-600">{buildDescString(parts)}</span>
        </p>
      )}
    </div>
  )
}

// ─── SVG Diagrams ─────────────────────────────────────────────────────────────

interface DiagramDims { [key: string]: string | undefined }
interface DiagramData { shape: string; dims: DiagramDims }

function ChannelSVG({ dims = {}, size = "preview", activeKey }: { dims?: DiagramDims; size?: "preview" | "inline"; activeKey?: string | null }) {
  const isP = size === "preview"
  const w = isP ? 200 : 120; const h = isP ? 100 : 65; const fs = isP ? 10 : 9
  const baseColor = "#333"; const highlight = "#C62828"; const textColor = "#111"
  const getStroke = (key: string) => (activeKey === key ? highlight : baseColor)
  const getWidth = (key: string) => (activeKey === key ? (isP ? 3 : 2.2) : isP ? 2 : 1.5)
  const getTextFill = (key: string) => (activeKey === key ? highlight : textColor)
  return (
    <svg width={w} height={h} viewBox={`0 0 ${w} ${h}`} xmlns="http://www.w3.org/2000/svg">
      <text x={w / 2} y={isP ? 12 : 10} textAnchor="middle" fontSize={fs} fill={getTextFill("top")} fontWeight="bold">{dims.top || "Top"}</text>
      <line x1={w * 0.3} y1={isP ? 18 : 15} x2={w * 0.7} y2={isP ? 18 : 15} stroke={getStroke("top")} strokeWidth={getWidth("top")} />
      <line x1={w * 0.3} y1={isP ? 18 : 15} x2={w * 0.2} y2={isP ? 75 : 50} stroke={getStroke("height")} strokeWidth={getWidth("height")} />
      <line x1={w * 0.7} y1={isP ? 18 : 15} x2={w * 0.8} y2={isP ? 75 : 50} stroke={getStroke("length")} strokeWidth={getWidth("length")} />
      <line x1={w * 0.15} y1={isP ? 75 : 50} x2={w * 0.85} y2={isP ? 75 : 50} stroke={getStroke("bottom")} strokeWidth={getWidth("bottom")} />
      <text x={isP ? 10 : 4} y={isP ? 50 : 35} fontSize={fs - 1} fill={getTextFill("height")} fontWeight="bold">{dims.height || "H"}</text>
      <text x={w / 2} y={isP ? 90 : 62} textAnchor="middle" fontSize={fs} fill={getTextFill("bottom")} fontWeight="bold">{dims.bottom || "Bottom"}</text>
      <text x={isP ? w - 12 : w - 6} y={isP ? 50 : 35} fontSize={fs - 1} fill={getTextFill("length")} fontWeight="bold">{dims.length || "L"}</text>
    </svg>
  )
}

function LBracketSVG({ dims = {}, size = "preview", activeKey }: { dims?: DiagramDims; size?: "preview" | "inline"; activeKey?: string | null }) {
  const isP = size === "preview"
  const w = isP ? 240 : 160; const h = isP ? 110 : 78; const fs = isP ? 12 : 9
  const baseColor = "#222"; const highlight = "#C62828"
  const getStroke = (key: string) => (activeKey === key ? highlight : baseColor)
  const getWidth = (key: string) => (activeKey === key ? (isP ? 3 : 2.2) : isP ? 2 : 1.5)
  const lx = isP ? 40 : 30; const rx = isP ? 120 : 85
  const baseY = isP ? 85 : 55; const ltY = isP ? 12 : 10; const rtY = isP ? 22 : 16; const bRx = isP ? 220 : 145
  const parseDimensionValue = (value: string | undefined) => {
    if (!value) return { whole: "", frac: "" }
    const match = value.trim().match(/^(\d+)?\s*(\d+\/\d+)?/)
    return { whole: match?.[1] || "", frac: match?.[2] || "" }
  }
  const renderDimension = (value: string | undefined, fallback: string, x: number, y: number, anchor: string) => {
    const { whole, frac } = parseDimensionValue(value || fallback)
    const actualWhole = whole || fallback
    if (!frac) {
      return <text key={`${x}-${y}`} x={x} y={y} fontSize={fs} textAnchor={anchor} fontWeight="bold" dominantBaseline="middle">{actualWhole}</text>
    }
    return (
      <g key={`${x}-${y}`}>
        <text x={x} y={y} fontSize={fs} textAnchor={anchor} fontWeight="bold" dominantBaseline="middle">{actualWhole}</text>
        <text x={x + (isP ? 20 : 14)} y={y} fontSize={fs - 2} textAnchor="start" fontWeight="bold" dominantBaseline="middle">
          <tspan x={x + (isP ? 20 : 14)} dy="0">{frac.split("/")[0]}</tspan>
          <tspan x={x + (isP ? 20 : 14)} dy={isP ? 7 : 5} fontSize={fs - 3} textAnchor="start">─</tspan>
          <tspan x={x + (isP ? 20 : 14)} dy={isP ? 7 : 5}>{frac.split("/")[1]}</tspan>
        </text>
      </g>
    )
  }
  return (
    <svg width={w} height={h} viewBox={`0 0 ${w} ${h}`}>
      <line x1={lx} y1={ltY} x2={lx} y2={baseY} stroke={getStroke("leftH")} strokeWidth={getWidth("leftH")} />
      <line x1={lx} y1={baseY} x2={bRx} y2={baseY} stroke={getStroke("bottomW")} strokeWidth={getWidth("bottomW")} />
      <line x1={rx} y1={rtY} x2={rx} y2={baseY} stroke={getStroke("rightH")} strokeWidth={getWidth("rightH")} />
      {renderDimension(dims.leftH, "15", lx - 18, (ltY + baseY) / 2 + 3, "end")}
      {renderDimension(dims.rightH, "15", rx + 12, (rtY + baseY) / 2 + 3, "start")}
      {renderDimension(dims.inner, "13", (lx + rx) / 2, baseY + 18, "middle")}
      {renderDimension(dims.bottomW, "36", (rx + bRx) / 2, baseY + 18, "middle")}
    </svg>
  )
}

function RectSVG({ dims = {}, size = "preview", activeKey }: { dims?: DiagramDims; size?: "preview" | "inline"; activeKey?: string | null }) {
  const isP = size === "preview"
  const w = isP ? 200 : 90; const h = isP ? 80 : 45
  const fillColor = isP ? "var(--color-text-secondary,#666)" : "#555"; const fs = isP ? 10 : 7
  const baseColor = "#333"; const highlight = "#C62828"
  const getTextFill = (key: string) => (activeKey === key ? highlight : fillColor)
  const rectStroke = activeKey === "width" || activeKey === "height" ? highlight : baseColor
  const rectWidth = activeKey === "width" || activeKey === "height" ? (isP ? 3 : 2.2) : 2
  return (
    <svg width={w} height={h} viewBox={`0 0 ${w} ${h}`} xmlns="http://www.w3.org/2000/svg">
      <rect x={w * 0.18} y={10} width={w * 0.64} height={h - 20} fill="none" stroke={rectStroke} strokeWidth={rectWidth} rx={2} />
      <text x={w / 2} y={8} textAnchor="middle" fontSize={fs} fill={getTextFill("width")} fontWeight={activeKey === "width" ? "bold" : "normal"}>{dims.width || "W"}</text>
      <text x={w * 0.88} y={h / 2} fontSize={fs} fill={getTextFill("height")} fontWeight={activeKey === "height" ? "bold" : "normal"}>{dims.height || "H"}</text>
    </svg>
  )
}

function DiagramRenderer({ diagram = {}, size = "preview", activeKey }: { diagram?: DiagramData; size?: "preview" | "inline"; activeKey?: string | null }) {
  if (diagram.shape === "lbracket") return <LBracketSVG dims={diagram.dims} size={size} activeKey={activeKey} />
  if (diagram.shape === "channel") return <ChannelSVG dims={diagram.dims} size={size} activeKey={activeKey} />
  if (diagram.shape === "rect") return <RectSVG dims={diagram.dims} size={size} activeKey={activeKey} />
  if (diagram.shape === "custom") return <span>{diagram.dims?.note}</span>
  return null
}

// ─── Diagram SVG for PDF ──────────────────────────────────────────────────────

function renderDiagramHTML(diagram: DiagramData): string {
  const d = diagram.dims
  if (diagram.shape === "channel") {
    return `<svg width="260" height="170" viewBox="0 0 260 170" display="block" xmlns="http://www.w3.org/2000/svg">
      <text x="130" y="16" text-anchor="middle" font-size="14" fill="#111" font-weight="bold">${d.top || ""}</text>
      <line x1="78" y1="28" x2="182" y2="28" stroke="#333" stroke-width="2.5"/>
      <line x1="78" y1="28" x2="52" y2="120" stroke="#333" stroke-width="2.5"/>
      <line x1="182" y1="28" x2="208" y2="120" stroke="#333" stroke-width="2.5"/>
      <line x1="38" y1="120" x2="222" y2="120" stroke="#333" stroke-width="2.5"/>
      <text x="8" y="82" font-size="13" fill="#111" font-weight="bold">${d.height || ""}</text>
      <text x="130" y="155" text-anchor="middle" font-size="14" fill="#111" font-weight="bold">${d.bottom || ""}</text>
      <text x="252" y="82" font-size="13" fill="#111" font-weight="bold" text-anchor="end">${d.length || ""}</text>
    </svg>`
  }
  if (diagram.shape === "lbracket") {
    return `<svg width="320" height="160" viewBox="0 0 320 160" display="block" xmlns="http://www.w3.org/2000/svg">
      <line x1="55" y1="16" x2="55" y2="118" stroke="#222" stroke-width="3"/>
      <line x1="55" y1="118" x2="290" y2="118" stroke="#222" stroke-width="3"/>
      <line x1="175" y1="32" x2="175" y2="118" stroke="#222" stroke-width="3"/>
      <text x="26" y="72" font-size="13" fill="#444" text-anchor="end">${d.leftH || ""}</text>
      <text x="192" y="80" font-size="13" fill="#444">${d.rightH || ""}</text>
      <text x="115" y="148" font-size="13" fill="#444" text-anchor="middle">${d.inner || ""}</text>
      <text x="234" y="148" font-size="13" fill="#444" text-anchor="middle">${d.bottomW || ""}</text>
    </svg>`
  }
  if (diagram.shape === "rect") {
    return `<svg width="200" height="110" viewBox="0 0 200 110" display="block" xmlns="http://www.w3.org/2000/svg">
      <rect x="28" y="14" width="144" height="72" fill="none" stroke="#333" stroke-width="2.5" rx="2"/>
      <text x="100" y="11" text-anchor="middle" font-size="13" fill="#555" font-weight="bold">${d.width || ""}</text>
      <text x="182" y="56" font-size="12" fill="#555" font-weight="bold">${d.height || ""}</text>
    </svg>`
  }
  if (diagram.shape === "custom") {
    return `<span style="font-size:14px;color:#555;">${d.note || ""}</span>`
  }
  return ""
}

// ─── Diagram Dimension Input ──────────────────────────────────────────────────

function DiagramDimInput({ value, onChange, onFocus, onBlur }: { value: string; onChange: (v: string) => void; onFocus: () => void; onBlur: () => void }) {
  const parseValue = (val: string) => {
    const match = val.match(/^(\d+)?\s*(\d+\/\d+)?\s*([a-zA-Z"']*)?$/)
    if (match) return { whole: match[1] || "", frac: match[2] || "", unit: match[3] || "" }
    return { whole: "", frac: "", unit: "" }
  }
  const parsed = parseValue(value || "")
  const [whole, setWhole] = useState(parsed.whole)
  const [frac, setFrac] = useState(parsed.frac)
  const [unit, setUnit] = useState(parsed.unit)
  const wholeRef = useRef(whole); const fracRef = useRef(frac); const unitRef = useRef(unit)
  useEffect(() => { wholeRef.current = whole; fracRef.current = frac; unitRef.current = unit }, [whole, frac, unit])
  useEffect(() => { const p = parseValue(value || ""); setWhole(p.whole); setFrac(p.frac); setUnit(p.unit) }, [value])
  const buildValue = (w: string, f: string, u: string) => { const parts = []; if (w) parts.push(w); if (f) parts.push(f); return parts.join(" ") + u }
  const handleWholeChange = (v: string) => { setWhole(v); onChange(buildValue(v, fracRef.current, unitRef.current)) }
  const handleFracChange = (v: string) => { setFrac(v); onChange(buildValue(wholeRef.current, v, unitRef.current)) }
  const handleUnitChange = (v: string) => { setUnit(v); onChange(buildValue(wholeRef.current, fracRef.current, v)) }
  const inCls = "border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-[#C62828] text-xs px-1.5 py-1.5 bg-white"
  const lbl = "text-[9px] font-medium text-gray-400 text-center block mb-0.5"
  return (
    <div className="flex items-end gap-1" onFocus={onFocus} onBlur={onBlur}>
      <div><span className={lbl}>Whole</span><input className={inCls} style={{ width: 38 }} value={whole} onChange={(e) => handleWholeChange(e.target.value.replace(/\D/g, ""))} placeholder="12" onFocus={onFocus} onBlur={onBlur} /></div>
      <div><span className={lbl}>Frac</span><FractionInput value={frac} onChange={handleFracChange} /></div>
      <div><span className={lbl}>Unit</span>
        <select className={inCls} style={{ width: 46 }} value={unit} onChange={(e) => handleUnitChange(e.target.value)} onFocus={onFocus} onBlur={onBlur}>
          {UNIT_OPTIONS.map((u) => <option key={u} value={u}>{u || "—"}</option>)}
        </select>
      </div>
    </div>
  )
}

// ─── Diagram Editor Modal ─────────────────────────────────────────────────────

const SHAPE_FIELDS: Record<string, { k: string; l: string }[]> = {
  channel: [{ k: "top", l: "Top width" }, { k: "height", l: "Height" }, { k: "bottom", l: "Bottom width" }, { k: "length", l: "Length / depth" }],
  lbracket: [{ k: "leftH", l: "Left arm height" }, { k: "rightH", l: "Right arm height" }, { k: "inner", l: "Inner width (between arms)" }, { k: "bottomW", l: "Base total width" }],
  rect: [{ k: "width", l: "Width" }, { k: "height", l: "Height" }],
  custom: [{ k: "note", l: "Description / dimensions text" }],
}

interface QuotationItem { id: string; sku: string; desc: string; count: string; diagram: DiagramData | null }

function DiagramModal({ item, onSave, onClose }: { item: QuotationItem; onSave: (diagram: DiagramData, count: string) => void; onClose: () => void }) {
  const [shape, setShape] = useState(item?.diagram?.shape || "channel")
  const [dims, setDims] = useState<DiagramDims>(item?.diagram?.dims || {})
  const [count, setCount] = useState(item?.count || "")
  const chg = (s: string) => { setShape(s); if (s !== shape) setDims({}) }
  const [activeKey, setActiveKey] = useState<string | null>(null)
  const labels: Record<string, string> = { channel: "Channel", lbracket: "L-bracket", rect: "Rectangle", custom: "Text only" }
  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-md">
        <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between">
          <h2 className="text-lg font-semibold text-gray-900">{item?.diagram ? "Edit" : "Add"} diagram — {item?.sku}</h2>
          <button onClick={onClose} className="p-1 hover:bg-gray-100 rounded-lg"><X className="w-5 h-5 text-gray-500" /></button>
        </div>
        <div className="p-6 space-y-5">
          <div>
            <p className="text-xs font-medium text-gray-600 mb-2">Shape type</p>
            <div className="flex flex-wrap gap-2">
              {Object.entries(labels).map(([s, l]) => (
                <button key={s} onClick={() => chg(s)} className={`px-3 py-1.5 text-sm rounded-lg border transition-colors ${shape === s ? "bg-[#C62828] text-white border-[#C62828]" : "border-gray-300 text-gray-700 hover:bg-gray-50"}`}>{l}</button>
              ))}
            </div>
          </div>
          <div className="border border-gray-200 rounded-lg p-4 flex items-center justify-center min-h-[110px] bg-gray-50">
            <DiagramRenderer diagram={{ shape, dims }} size="preview" activeKey={activeKey} />
          </div>
          <div className="grid grid-cols-2 gap-4">
            {(SHAPE_FIELDS[shape] || []).map((f) => (
              <div key={f.k} className={f.k === "note" ? "col-span-2" : ""}>
                <label className="block text-xs font-medium text-gray-600 mb-1.5">{f.l}</label>
                {f.k === "note" ? (
                  <input value={dims[f.k] || ""} onFocus={() => setActiveKey(f.k)} onBlur={() => setActiveKey(null)} onChange={(e) => setDims((d) => ({ ...d, [f.k]: e.target.value }))} className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#C62828] text-sm" />
                ) : (
                  <DiagramDimInput value={dims[f.k] || ""} onChange={(v) => setDims((d) => ({ ...d, [f.k]: v }))} onFocus={() => setActiveKey(f.k)} onBlur={() => setActiveKey(null)} />
                )}
              </div>
            ))}
          </div>
        </div>
        <div className="px-6 py-4 border-t border-gray-200 flex gap-3 justify-end items-center">
          <div className="flex items-center gap-2 mr-auto">
            <label className="text-xs font-medium text-gray-600">Count</label>
            <input
              value={count}
              onChange={(e) => setCount(e.target.value.replace(/\D/g, ""))}
              placeholder="1"
              className="w-16 px-2 py-1.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#C62828]"
            />
            <span className="text-xs text-gray-500">No</span>
          </div>
          <button onClick={onClose} className="px-4 py-2 border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50">Cancel</button>
          <button onClick={() => onSave({ shape, dims }, count)} className="px-4 py-2 bg-[#C62828] text-white rounded-lg text-sm font-medium hover:bg-[#B71C1C]">Save diagram</button>
        </div>
      </div>
    </div>
  )
}

// ─── Preview Modal ────────────────────────────────────────────────────────────

interface QuotationData {
  date: string; machineName: string; items: QuotationItem[]
  ownerName: string
}

function PreviewModal({ data, onClose, onDownload, generating }: { data: QuotationData; onClose: () => void; onDownload: () => void; generating: boolean }) {
  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
          <h2 className="text-xl font-bold text-[#C62828]">Quotation preview</h2>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg"><X className="w-5 h-5" /></button>
        </div>
        <div className="p-8">
          <div className="mb-6 flex items-center gap-4 border-b-2 border-[#40B7FF] pb-2">
            <img src={`data:image/jpeg;base64,${SGH_LOGO_B64}`} alt="SGH Logo" style={{ width: 94, height: 64, objectFit: "contain", flexShrink: 0 }} />
            <div className="flex-4">
              <h2 className="text-xl font-bold text-[#C62828] mb-1 text-center">SELVA GANAPATHI HYDRAULICS</h2>
              <p className="text-xs text-[#40B7FF] text-center">487, Gandhi Nagar Road, KUNNATHUR - 638103, Tirupur (Dt).</p>
              <p className="text-xs text-[#40B7FF] text-center">Email: sgharasu@gmail.com | Cell: 75026 21020, 74026 21020</p>
            </div>
          </div>
          <div className="mb-4">
            <p className="text-right text-sm font-semibold mb-2">Date: {data.date}</p>
          </div>
          <h3 className="font-bold underline text-base mb-3">{data.machineName}</h3>
          <table className="w-full border-collapse text-xs mb-4">
            <thead>
              <tr className="bg-gray-100">
                <th className="border border-gray-300 px-2 py-2 text-left w-8">S.No</th>
                <th className="border border-gray-300 px-2 py-2 text-left w-16">Material</th>
                <th className="border border-gray-300 px-2 py-2 text-left">Length</th>
                <th className="border border-gray-300 px-2 py-2 text-center w-10">No</th>
              </tr>
            </thead>
            <tbody>
              {data.items.filter((i) => i.desc.trim() || i.diagram).map((item, idx) => {
                const parts = parseDescString(item.desc)
                const countVal = item.diagram ? item.count : parts.count
                return (
                  <tr key={item.id}>
                    <td className="border border-gray-300 px-2 py-2 font-semibold text-center">{idx + 1}</td>
                    <td className="border border-gray-300 px-2 py-2 font-semibold text-center">{item.sku}</td>
                    <td className="border border-gray-300 px-2 py-2">
                      {item.diagram ? <DiagramRenderer diagram={item.diagram} size="inline" /> : <DescDisplay desc={item.desc} showCount={false} />}
                    </td>
                    <td className="border border-gray-300 px-2 py-2 text-center font-semibold">
                      {countVal || ""}
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
          <div className="text-sm mb-4">
          </div>
          <div className="flex justify-end mt-6 pt-6 border-t border-gray-300">
          
          </div>
        </div>
        <div className="bg-gray-50 border-t border-gray-200 px-6 py-4 flex gap-3 justify-end">
          <button onClick={onClose} className="px-4 py-2 border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-100">Close</button>
          <button onClick={onDownload} disabled={generating} className="px-4 py-2 bg-[#C62828] text-white rounded-lg text-sm font-medium hover:bg-[#B71C1C] flex items-center gap-2 disabled:opacity-50">
            {generating ? (<><div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />Generating...</>) : (<><Download className="w-4 h-4" />Download PDF</>)}
          </button>
        </div>
      </div>
    </div>
  )
}

// ─── Inline Edit Row ──────────────────────────────────────────────────────────

function InlineEditRow({ item, idx, onSave, onCancel }: { item: QuotationItem; idx: number; onSave: (vals: { sku: string; desc: string; count: string }) => void; onCancel: () => void }) {
  const [sku, setSku] = useState(item.sku)
  const [desc, setDesc] = useState(item.desc)
  const [count, setCount] = useState(item.count || "")
  return (
    <div className="grid grid-cols-12 gap-2 px-3 py-3 items-start border-b border-gray-200 bg-yellow-50">
      <div className="col-span-1 text-xs font-semibold text-gray-500 pt-2">{idx + 1}</div>
      <div className="col-span-2"><input className="w-full px-2 py-1 text-xs border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-[#C62828]" value={sku} onChange={(e) => setSku(e.target.value)} placeholder="SKU" /></div>
      <div className="col-span-6">
        {item.diagram
          ? <div className="flex items-center gap-2 pt-1">
              <p className="text-xs text-gray-400 italic">Diagram item — edit via diagram button</p>
              <input
                className="w-14 px-2 py-1 text-xs border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-[#C62828]"
                value={count}
                onChange={(e) => setCount(e.target.value.replace(/\D/g, ""))}
                placeholder="Count"
              />
              <span className="text-xs text-gray-500">No</span>
            </div>
          : <DescEditor value={desc} onChange={setDesc} />
        }
      </div>
      <div className="col-span-2 flex gap-1 justify-end pt-1">
        <button onClick={() => onSave({ sku, desc: item.diagram ? item.desc : desc, count: item.diagram ? count : "" })} className="p-1.5 text-green-600 hover:bg-green-50 rounded"><Check className="w-4 h-4" /></button>
        <button onClick={onCancel} className="p-1.5 text-gray-500 hover:bg-gray-100 rounded"><X className="w-4 h-4" /></button>
      </div>
    </div>
  )
}

// ─── Add Item Panel ───────────────────────────────────────────────────────────

function AddItemPanel({ onAdd }: { onAdd: (item: { sku: string; desc: string; mode: string }) => void }) {
  const [mode, setMode] = useState("text")
  const [sku, setSku] = useState("")
  const [desc, setDesc] = useState("")
  const inputCls = "w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#C62828] text-sm"
  const handleAdd = () => {
    if (mode === "text" && !desc.trim()) { alert("Please enter a description."); return }
    onAdd({ sku, desc, mode }); setSku(""); setDesc("")
  }
  return (
    <div className="mt-4 p-4 bg-blue-50 rounded-lg border border-blue-200">
      <p className="text-xs font-semibold text-gray-700 mb-3">Add new specification</p>
      <div className="flex gap-2 mb-4">
        {["text", "diagram"].map((m) => (
          <button key={m} onClick={() => setMode(m)} className={`px-4 py-1.5 text-xs font-semibold rounded-full border transition-colors ${mode === m ? "bg-[#C62828] text-white border-[#C62828]" : "border-gray-300 text-gray-600 hover:bg-gray-100"}`}>
            {m === "text" ? "Text description" : "Diagram only"}
          </button>
        ))}
      </div>
      <div className="grid grid-cols-1 md:grid-cols-4 gap-3 items-end">
        <div>
          <label className="block text-xs font-medium text-gray-600 mb-1">SKU (optional)</label>
          <input className={inputCls} value={sku} onChange={(e) => setSku(e.target.value)} placeholder="e.g. 50mm" />
        </div>
        {mode === "text" ? (
          <div className="md:col-span-2">
            <label className="block text-xs font-medium text-gray-600 mb-2">Description fields</label>
            <DescEditor value={desc} onChange={setDesc} />
          </div>
        ) : (
          <div className="md:col-span-2 flex items-center">
            <p className="text-xs text-gray-500 italic bg-white border border-dashed border-gray-300 rounded-lg px-3 py-2 w-full">Diagram editor opens after adding — set count inside the diagram editor.</p>
          </div>
        )}
        <div>
          <button onClick={handleAdd} className="w-full px-4 py-2 bg-[#C62828] text-white rounded-lg text-sm font-medium hover:bg-[#B71C1C] flex items-center justify-center gap-1">
            <Plus className="w-4 h-4" /> Add
          </button>
        </div>
      </div>
    </div>
  )
}

// ─── Main ─────────────────────────────────────────────────────────────────────

const today = new Date()
const formattedDate = `${String(today.getDate()).padStart(2, "0")}/${String(today.getMonth() + 1).padStart(2, "0")}/${today.getFullYear()}`

const INITIAL_ITEMS: QuotationItem[] = [
  { id: "1",  sku: "50mm", desc: "3 1/2in x 20in - 2no",        count: "", diagram: null },
  { id: "2",  sku: "45mm", desc: "1 3/8in x 14Ft - 1no",         count: "", diagram: null },
  { id: "3",  sku: "40mm", desc: "4in x 7in - 1no",              count: "", diagram: null },
  { id: "4",  sku: "32mm", desc: "24in x 20in - 1no",            count: "", diagram: null },
  { id: "5",  sku: "32mm", desc: "24in x 22in - 1no",            count: "", diagram: null },
  { id: "6",  sku: "32mm", desc: "18in x 15in - 1no",            count: "", diagram: null },
  { id: "7",  sku: "28mm", desc: "6in x 20in - 2no",             count: "", diagram: null },
  { id: "8",  sku: "18mm", desc: "24in x 22in - 2no",            count: "", diagram: null },
  { id: "9",  sku: "18mm", desc: "24in x 15in - 1no",            count: "", diagram: null },
  { id: "10", sku: "16mm", desc: "18in x 14Ft - 1no",            count: "", diagram: null },
  { id: "11", sku: "16mm", desc: "5in x 14Ft - 2no",             count: "", diagram: null },
  { id: "12", sku: "16mm", desc: "7 1/2in x 12 3/4in - 4no",    count: "", diagram: null },
  { id: "13", sku: "16mm", desc: "8in x 22in - 2no",             count: "", diagram: null },
  { id: "14", sku: "16mm", desc: "1 1/8in x 22in - 1no",         count: "", diagram: null },
  { id: "15", sku: "16mm", desc: "15in x 22in - 1no",            count: "", diagram: null },
  { id: "16", sku: "16mm", desc: "10in x 10in - 1no",            count: "", diagram: null },
  { id: "17", sku: "16mm", desc: "8in x 8in - 2no",              count: "", diagram: null },
  { id: "18", sku: "12mm", desc: "8in x 8in - 2no",              count: "", diagram: null },
  { id: "19", sku: "8mm",  desc: "", count: "1", diagram: { shape: "channel",  dims: { top: "3in", height: '3 3/4in', bottom: "6in", length: '66"' } } },
  { id: "20", sku: "4mm",  desc: "2' x 4' - 1no",               count: "", diagram: null },
  { id: "21", sku: "4mm",  desc: "2' x 4' - 1no",               count: "", diagram: null },
  { id: "22", sku: "3mm",  desc: "", count: "1", diagram: { shape: "lbracket", dims: { leftH: "15 1/2", rightH: "15", inner: "13", bottomW: "36" } } },
  { id: "23", sku: "3mm",  desc: "14 3/4in x 12 3/4in - 4no",  count: "", diagram: null },
  { id: "24", sku: "3mm",  desc: "12 3/4in x 36 - 2no",         count: "", diagram: null },
]

export default function QuotationGenerator() {
  const [data, setData] = useState<QuotationData>({
    date: formattedDate, machineName: "ABQ", items: INITIAL_ITEMS,
    ownerName: "A.Thanikai Arasu",
  })
  const [editingId, setEditingId] = useState<string | null>(null)
  const [diagModalItem, setDiagModalItem] = useState<QuotationItem | null>(null)
  const [previewOpen, setPreviewOpen] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [nextId, setNextId] = useState(25)

  const upField = <K extends keyof QuotationData>(f: K, v: QuotationData[K]) => setData((p) => ({ ...p, [f]: v }))
  const upItems = (fn: (items: QuotationItem[]) => QuotationItem[]) => setData((p) => ({ ...p, items: fn(p.items) }))

  const saveEdit = (id: string, { sku, desc, count }: { sku: string; desc: string; count: string }) => {
    upItems((items) => items.map((it) => (it.id === id ? { ...it, sku, desc, count } : it)))
    setEditingId(null)
  }

  const deleteItem = (id: string) => {
    if (data.items.length <= 1) { alert("Must have at least one item."); return }
    upItems((items) => items.filter((it) => it.id !== id))
  }

  const addItem = ({ sku, desc, mode }: { sku: string; desc: string; mode: string }) => {
    const id = String(nextId); setNextId((n) => n + 1)
    const ni: QuotationItem = { id, sku: sku || "-", desc: mode === "diagram" ? "" : desc, count: "", diagram: null }
    upItems((items) => [...items, ni])
    if (mode === "diagram") setDiagModalItem(ni)
  }

  const saveDiagram = (diagram: DiagramData, count: string) => {
    upItems((items) => items.map((it) => (it.id === diagModalItem?.id ? { ...it, diagram, desc: "", count } : it)))
    setDiagModalItem(null)
  }

  const removeDiagram = (id: string) => upItems((items) => items.map((it) => (it.id === id ? { ...it, diagram: null } : it)))

  const buildHTML = () => {
    const filteredItems = data.items.filter((i) => i.desc.trim() || i.diagram)

    const rows = filteredItems.map((item, idx) => {
      const parts = parseDescString(item.desc)
      let descCell = ""
      let countCell = ""

      if (item.diagram) {
        descCell = renderDiagramHTML(item.diagram)
        countCell = item.count
          ? `<span style="font-weight:700;color:#1f2937;font-size:13px;">${item.count}</span>`
          : ""
      } else {
        descCell = renderDescHTML(item.desc, false)
        countCell = parts.count
          ? `<span style="font-weight:700;color:#1f2937;font-size:13px;">${parts.count}</span>`
          : ""
      }

      const rowBg = idx % 2 === 0 ? "#ffffff" : "#f9fafb"

      return `<tr style="background:${rowBg};page-break-inside:avoid;break-inside:avoid;">
        <td style="padding:9px 10px;border:1px solid #d1d5db;text-align:center;font-weight:700;font-size:13px;color:#374151;vertical-align:middle;">${idx + 1}</td>
        <td style="padding:9px 10px;border:1px solid #d1d5db;text-align:center;font-weight:700;font-size:13px;color:#374151;vertical-align:middle;">${item.sku}</td>
        <td style="padding:9px 10px;border:1px solid #d1d5db;vertical-align:middle;">${descCell}</td>
        <td style="padding:9px 10px;border:1px solid #d1d5db;text-align:center;vertical-align:middle;">${countCell}</td>
      </tr>`
    }).join("")

    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #111; }
    .page { width: 794px; padding: 32px 40px; }
    .header { margin-bottom: 24px; }
    .header-inner { display: flex; align-items: center; gap: 16px; border-bottom: 2.5px solid #40B7FF; padding-bottom: 8px; }
    .logo { width: 70px; height: 70px; object-fit: contain; flex-shrink: 0; }
    .header-text { flex: 1; }
    .header h2 { font-size: 22px; font-weight: 900; color: #C62828; letter-spacing: 0.5px; margin-bottom: 5px; text-align: center; }
    .divider { display: none; }
    .header p { font-size: 11px; color: #40B7FF; margin: 2px 0; text-align: center; }
    .meta { margin-bottom: 14px; }
    .meta-date { text-align: right; font-weight: 700; font-size: 13px; margin-bottom: 8px; }
    .machine-name { font-size: 16px; font-weight: 700; text-decoration: underline; margin-bottom: 12px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 18px; table-layout: fixed; }
    thead tr { background: #f3f4f6; }
    th { padding: 10px; border: 1px solid #d1d5db; text-align: left; font-size: 13px; font-weight: 700; color: #374151; }
    th.center { text-align: center; }
    td { vertical-align: middle; }
    tr { page-break-inside: avoid; break-inside: avoid; }
    .signature-row { display: flex; justify-content: flex-end; margin-top: 24px; }
    .signature-box { text-align: right; }
    .owner-name { font-weight: 700; font-size: 14px; color: #111; }
    .sig-line { margin-top: 28px; border-top: 1px solid #374151; padding-top: 4px; font-size: 11px; color: #9ca3af; width: 110px; text-align: center; }
    .no-gst { color: #374151; font-size: 13px; margin-top: 8px; }
  </style>
</head>
<body>
<div class="page">
  <div class="header">
    <div class="header-inner">
      <img class="logo" src="data:image/jpeg;base64,${SGH_LOGO_B64}" alt="SGH Logo" style={{ width: 94, height: 64, objectFit: "contain", flexShrink: 0 }} />
      
      <div class="header-text">
        <h2>SELVA GANAPATHI HYDRAULICS</h2>
        <p>487, Gandhi Nagar Road, KUNNATHUR - 638103, Tirupur (Dt).</p>
        <p>Email: sgharasu@gmail.com | Cell: 75026 21020, 74026 21020</p>
      </div>
    </div>
  </div>
  <div class="meta">
    <div class="meta-date">Date: ${data.date}</div>
  </div>
  <div class="machine-name">${data.machineName}</div>
  <table>
    <thead>
      <tr>
        <th class="center" style="width:52px;">S.No</th>
        <th class="center" style="width:90px;">Material</th>
        <th>Length</th>
        <th class="center" style="width:52px;">No</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <div>
  </div>
  <div class="signature-row">
 
  </div>
</div>
</body>
</html>`
  }

  const downloadPDF = async () => {
    if (!data.machineName.trim()) {
      alert("Please fill in machine name.")
      return
    }
    setGenerating(true)
    try {
      const html2canvas = (await import("html2canvas")).default
      const jsPDFModule = (await import("jspdf")).default

      const el = document.createElement("div")
      el.innerHTML = buildHTML()
      el.style.position = "fixed"
      el.style.left = "-9999px"
      el.style.top = "0"
      el.style.width = "794px"
      document.body.appendChild(el)

      const inner = (el.querySelector(".page") || el) as HTMLElement
      inner.style.width = "794px"
      inner.style.boxSizing = "border-box"

      await new Promise(r => setTimeout(r, 300))

      const canvas = await html2canvas(inner, {
        scale: 2,
        useCORS: true,
        logging: false,
        scrollX: 0,
        scrollY: 0,
        width: 794,
        height: inner.scrollHeight,
        windowWidth: 794,
        windowHeight: inner.scrollHeight,
      })

      const imgData = canvas.toDataURL("image/jpeg", 0.98)

      const mmPerPx = 210 / 794
      const finalW = 210
      const finalH = Math.ceil(inner.scrollHeight * mmPerPx)

      const pdf = new jsPDFModule({
        unit: "mm",
        format: [finalW, finalH],
        orientation: "portrait",
      })

      pdf.addImage(imgData, "JPEG", 0, 0, finalW, finalH)
      pdf.save(`${data.machineName.replace(/\s+/g, "_")}_Quotation_${data.date.replace(/\//g, "-")}.pdf`)

      document.body.removeChild(el)
    } catch (err) {
      console.error(err)
      alert("PDF generation failed.")
    } finally {
      setGenerating(false)
    }
  }

  const iCls = "w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#C62828] text-sm"
  const sTCls = "text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2"

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 p-6">
      <div className="max-w-5xl mx-auto space-y-6">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <div className="w-2 h-8 bg-[#C62828] rounded-full" />
            <h1 className="text-3xl font-bold text-gray-900">Quotation Generator</h1>
          </div>
          <p className="text-gray-500 ml-5 text-sm">{data.items.length} items · diagram support · structured description editor</p>
        </div>

        {/* Basic Info */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
          <h2 className={sTCls}><span className="w-1 h-6 bg-[#C62828] rounded-full" />Basic information</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
            <div><label className="block text-xs font-medium text-gray-600 mb-1">Date</label><input className={iCls} value={data.date} onChange={(e) => upField("date", e.target.value)} /></div>
            <div><label className="block text-xs font-medium text-gray-600 mb-1">Machine / order name</label><input className={iCls} value={data.machineName} onChange={(e) => upField("machineName", e.target.value)} /></div>
          </div>
          <div><label className="block text-xs font-medium text-gray-600 mb-1">Owner / signatory name</label><input className={iCls} value={data.ownerName} onChange={(e) => upField("ownerName", e.target.value)} /></div>
        </div>

        {/* Items */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className={sTCls} style={{ marginBottom: 0 }}><span className="w-1 h-6 bg-[#C62828] rounded-full" />Order items / specifications</h2>
            <span className="bg-[#C62828] text-white text-xs font-semibold px-3 py-1 rounded-full">{data.items.length} items</span>
          </div>
          <div className="grid grid-cols-12 gap-2 px-3 py-2 bg-gray-50 rounded-t-lg border border-gray-200 text-xs font-semibold text-gray-700">
            <div className="col-span-1">S.No</div>
            <div className="col-span-2">Material</div>
            <div className="col-span-6">Length</div>
            <div className="col-span-1 text-center">No</div>
            <div className="col-span-2 text-right">Actions</div>
          </div>
          <div className="border border-t-0 border-gray-200 rounded-b-lg overflow-hidden max-h-[520px] overflow-y-auto">
            {data.items.map((item, idx) =>
              editingId === item.id ? (
                <InlineEditRow key={item.id} item={item} idx={idx} onSave={(vals) => saveEdit(item.id, vals)} onCancel={() => setEditingId(null)} />
              ) : (
                <div key={item.id} className="grid grid-cols-12 gap-2 px-3 py-2 items-center border-b border-gray-200 hover:bg-gray-50 transition-colors">
                  <div className="col-span-1 text-xs font-semibold text-gray-400">{idx + 1}</div>
                  <div className="col-span-2 text-xs font-semibold text-gray-700">{item.sku}</div>
                  <div className="col-span-6">
                    {item.diagram ? (
                      <div className="flex items-center gap-3">
                        <DiagramRenderer diagram={item.diagram} size="inline" />
                        <div className="flex flex-col gap-1">
                          <button onClick={() => setDiagModalItem(item)} className="text-xs text-blue-500 hover:text-blue-700 underline">Edit diagram</button>
                          <button onClick={() => removeDiagram(item.id)} className="text-xs text-red-400 hover:text-red-600">Remove</button>
                        </div>
                      </div>
                    ) : (
                      <DescDisplay desc={item.desc} showCount={false} />
                    )}
                  </div>
                  <div className="col-span-1 text-center">
                    <span className="text-xs font-semibold text-gray-700">
                      {item.diagram ? item.count : parseDescString(item.desc).count}
                    </span>
                  </div>
                  <div className="col-span-2 flex gap-1 justify-end">
                    <button onClick={() => setEditingId(item.id)} className="p-1.5 text-blue-500 hover:bg-blue-50 rounded"><Edit2 className="w-3.5 h-3.5" /></button>
                    <button onClick={() => deleteItem(item.id)} className="p-1.5 text-red-500 hover:bg-red-50 rounded"><Trash2 className="w-3.5 h-3.5" /></button>
                  </div>
                </div>
              )
            )}
          </div>
          <AddItemPanel onAdd={addItem} />
        </div>

        {/* Actions */}
        <div className="flex gap-4 flex-wrap pb-8">
          <button onClick={() => setPreviewOpen(true)} className="px-6 py-3 border-2 border-[#C62828] text-[#C62828] rounded-lg font-semibold hover:bg-[#C62828] hover:text-white transition-colors flex items-center gap-2">
            <Eye className="w-5 h-5" /> Preview
          </button>
          <button onClick={downloadPDF} disabled={generating} className="px-6 py-3 bg-[#C62828] hover:bg-[#B71C1C] text-white rounded-lg font-semibold transition-colors flex items-center gap-2 disabled:opacity-50">
            {generating ? (<><div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />Generating...</>) : (<><Download className="w-5 h-5" />Download PDF</>)}
          </button>
        </div>
      </div>

      {diagModalItem && <DiagramModal item={diagModalItem} onSave={saveDiagram} onClose={() => setDiagModalItem(null)} />}
      {previewOpen && <PreviewModal data={data} onClose={() => setPreviewOpen(false)} onDownload={() => { setPreviewOpen(false); downloadPDF() }} generating={generating} />}
    </div>
  )
}